-- +goose Up
-- Closes the Solidity-vs-SQL gaps found by the v3.1-2026-08-19 event audit.
--
-- 1. cg_fund_transf_err gains the event's errStr (the wording the emitting
--    contract attached; NULL for rows indexed before this migration).
--    The CST staking wallet's tryPerformMaintenance emission is now
--    dispatched as well (registry change), so the column matters again.
-- 2. cg_nft_unstaked_rwalk gains action_counter, matching cg_nft_unstaked_cst
--    (IStakingWalletRandomWalkNft.NftUnstaked emits it; it was dropped).
-- 3. cg_staking_eth_deposit gains reward_per_staked_nft, the contract's
--    all-time cumulative reward per staked NFT carried by EthDepositReceived,
--    and the insert trigger now maintains accum_modulo as the running sum of
--    the discarded division remainders (the indexer used to write 0).
-- 4. cg_error_lookup: signature -> message for every custom error and every
--    failure event, generated by scripts/gen-cg-error-lookup.py. V3 removed
--    most errStr parameters from the custom errors, so the description of a
--    revert selector lives only here.
-- 5. Tables for the OpenZeppelin events the deployed contracts inherit and
--    the ETL did not store: ERC-721/ERC-20 approvals, ERC-20 Votes
--    delegation, EIP712DomainChanged, and the Governor events of
--    CosmicSignatureDao.
--
-- Rows indexed before this migration keep NULL in the new nullable columns;
-- replaying the affected events (delete-then-insert by evtlog id) fills them.

ALTER TABLE cg_fund_transf_err ADD COLUMN err_str TEXT;
ALTER TABLE cg_nft_unstaked_rwalk ADD COLUMN action_counter BIGINT;
ALTER TABLE cg_staking_eth_deposit ADD COLUMN reward_per_staked_nft DECIMAL;

-- Running remainder sum for rows inserted before the trigger maintained it.
UPDATE cg_staking_eth_deposit d
	SET accum_modulo = s.running
	FROM (
		SELECT id, SUM(modulo) OVER (ORDER BY deposit_id, id) AS running
		FROM cg_staking_eth_deposit
	) s
	WHERE d.id = s.id;

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION on_eth_deposit_insert() RETURNS trigger AS  $$
DECLARE
	v_amount_per_token DECIMAL;
	v_mod DECIMAL;
	v_rec RECORD;
	v_cnt						NUMERIC;
	v_prev_num_tokens		INT;
	v_prev_amount			DECIMAL;
	v_prev_amount_per_token	DECIMAL;
	v_prev_accum_modulo		DECIMAL;
	v_tokens_added			INT;
BEGIN

	IF NEW.num_staked_nfts > 0 THEN
		SELECT accumulated_nfts,accumulated_amount,accumulated_per_token,accum_modulo FROM cg_staking_eth_deposit ORDER BY deposit_id DESC OFFSET 1 LIMIT 1 INTO v_prev_num_tokens,v_prev_amount,v_prev_amount_per_token,v_prev_accum_modulo;
		IF v_prev_num_tokens IS NULL THEN
			v_prev_num_tokens:=0;
			v_tokens_added:=NEW.num_staked_nfts;
		ELSE
			v_tokens_added:=NEW.num_staked_nfts-v_prev_num_tokens;
		END IF;
		IF v_prev_amount IS NULL THEN
			v_prev_amount:=0;
		END IF;
		IF v_prev_amount_per_token IS NULL THEN
			v_prev_amount_per_token:=0;
		END IF;
		IF v_prev_accum_modulo IS NULL THEN
			v_prev_accum_modulo:=0;
		END IF;
		v_mod := MOD(NEW.deposit_amount,NEW.num_staked_nfts);
		v_amount_per_token := (NEW.deposit_amount - v_mod) / NEW.num_staked_nfts;
		UPDATE cg_staker_cst
			SET total_reward = (total_reward + (v_amount_per_token*total_tokens_staked)),
				unclaimed_reward = (unclaimed_reward + (v_amount_per_token*total_tokens_staked))
			WHERE total_tokens_staked > 0;
		UPDATE cg_stake_stats_cst
			SET
				total_reward_amount = (total_reward_amount + (NEW.deposit_amount - v_mod)),
				total_unclaimed_reward = (total_unclaimed_reward + (NEW.deposit_amount - v_mod)),
				num_deposits = (num_deposits + 1),
				total_modulo = (total_modulo + v_mod)
			;
		FOR v_rec IN (SELECT count(*) AS num_toks,staker_aid FROM cg_staked_token_cst GROUP BY staker_aid)
		LOOP
			INSERT INTO cg_staker_deposit(staker_aid,deposit_id,tokens_staked,amount_to_claim,amount_deposited)
				VALUES(v_rec.staker_aid,NEW.deposit_id,v_rec.num_toks,v_amount_per_token*v_rec.num_toks,v_amount_per_token*v_rec.num_toks);
		END LOOP;
		FOR v_rec IN (SELECT token_id,stake_action_id,staker_aid FROM cg_staked_token_cst)
		LOOP
			UPDATE cg_staked_token_cst_rewards 
				SET accumulated_reward = (accumulated_reward + v_amount_per_token)
				WHERE stake_action_id=v_rec.stake_action_id;
			GET DIAGNOSTICS v_cnt = ROW_COUNT;
			IF v_cnt = 0 THEN
				INSERT INTO cg_staked_token_cst_rewards(staker_aid,token_id,stake_action_id,accumulated_reward)
					VALUES(v_rec.staker_aid,v_rec.token_id,v_rec.stake_action_id,v_amount_per_token);
			END IF;
			INSERT INTO cg_st_reward(staker_aid,action_id,token_id,deposit_id,round_num,reward)
				VALUES(v_rec.staker_aid,v_rec.stake_action_id,v_rec.token_id,NEW.deposit_id,NEW.round_num,v_amount_per_token);
		END LOOP;
		UPDATE cg_staking_eth_deposit 
			SET 
				
				accumulated_amount = (v_prev_amount + NEW.deposit_amount),
				accumulated_per_token = (v_prev_amount_per_token + v_amount_per_token),
				accumulated_nfts = num_staked_nfts,
				accum_modulo = (v_prev_accum_modulo + v_mod),
				num_staked_nfts = v_tokens_added
			WHERE id=NEW.id;
	END IF;

	-- Insert record in cg_prize table with ptype=15 for Staking Deposit ETH (for CS NFT stakers)
	-- Using winner_index=0 to indicate this is a general staking reward, not a specific winner's prize
	INSERT INTO cg_prize(round_num,winner_index,ptype) VALUES(NEW.round_num,0,15);

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TABLE cg_error_lookup ( -- contract error / failure-event signature -> message (scripts/gen-cg-error-lookup.py)
	signature		TEXT PRIMARY KEY,		-- hex, no 0x: 64 chars (topic0) for events, 8 chars (selector) for custom errors
	kind			TEXT NOT NULL CHECK (kind IN ('event','error')),
	name			TEXT NOT NULL,			-- Solidity name
	abi_signature	TEXT NOT NULL,			-- canonical ABI signature the hash is derived from
	source			TEXT NOT NULL,			-- declaring Solidity file
	err_str			TEXT,					-- message the contracts attach (first variant); NULL when the signature carries none
	err_strs		TEXT[] NOT NULL DEFAULT '{}'	-- every distinct message used with this signature
);
INSERT INTO cg_error_lookup(signature, kind, name, abi_signature, source, err_str, err_strs) VALUES
	('35465b31', 'error', 'BidCstRewardAmountMinLimitNotReached', 'BidCstRewardAmountMinLimitNotReached(uint256,uint256)', 'CosmicSignatureErrors.sol', NULL, '{}'::TEXT[]),
	('df784b32', 'error', 'BidHasBeenPlacedInCurrentRound', 'BidHasBeenPlacedInCurrentRound()', 'CosmicSignatureErrors.sol', 'A bid has already been placed in the current bidding round.', ARRAY['A bid has already been placed in the current bidding round.']::TEXT[]),
	('87216cf2', 'error', 'CallerIsNotNftOwner', 'CallerIsNotNftOwner(address,uint256,address)', 'CosmicSignatureErrors.sol', NULL, '{}'::TEXT[]),
	('176a71b0', 'error', 'DonatedNftAlreadyClaimed', 'DonatedNftAlreadyClaimed(address,uint256)', 'CosmicSignatureErrors.sol', 'Donated NFT already claimed.', ARRAY['Donated NFT already claimed.']::TEXT[]),
	('e7ca2cb6', 'error', 'DonatedNftClaimDenied', 'DonatedNftClaimDenied(address,uint256,uint256,uint256)', 'CosmicSignatureErrors.sol', NULL, '{}'::TEXT[]),
	('eabe2ba4', 'error', 'DonatedTokenClaimDenied', 'DonatedTokenClaimDenied(uint256,address,address,uint256,uint256)', 'CosmicSignatureErrors.sol', NULL, '{}'::TEXT[]),
	('05dc9a46', 'error', 'EthWithdrawalDenied', 'EthWithdrawalDenied(uint256,address,address,uint256,uint256)', 'CosmicSignatureErrors.sol', NULL, '{}'::TEXT[]),
	('dc81d958', 'error', 'FirstRound', 'FirstRound()', 'CosmicSignatureErrors.sol', 'This operation is invalid during the very first bidding round.', ARRAY['This operation is invalid during the very first bidding round.']::TEXT[]),
	('154fb6c6', 'error', 'FundTransferFailed', 'FundTransferFailed(string,address,uint256)', 'CosmicSignatureErrors.sol', 'ETH transfer to charity failed.', ARRAY['ETH transfer to charity failed.','NFT staking ETH reward payment failed.']::TEXT[]),
	('7903b860', 'error', 'InsufficientReceivedBidAmount', 'InsufficientReceivedBidAmount(uint256,uint256)', 'CosmicSignatureErrors.sol', 'The current CST bid price is greater than the maximum you allowed.', ARRAY['The current CST bid price is greater than the maximum you allowed.','The current ETH bid price is greater than the amount you transferred.']::TEXT[]),
	('ce01a0a5', 'error', 'InvalidDonatedNftIndex', 'InvalidDonatedNftIndex(address,uint256)', 'CosmicSignatureErrors.sol', 'Invalid donated NFT index.', ARRAY['Invalid donated NFT index.']::TEXT[]),
	('2d6ebd6f', 'error', 'InvalidOperationInCurrentState', 'InvalidOperationInCurrentState()', 'CosmicSignatureErrors.sol', 'Too early.', ARRAY['Too early.']::TEXT[]),
	('2c57366e', 'error', 'MainPrizeClaimDenied', 'MainPrizeClaimDenied(address,address,uint256)', 'CosmicSignatureErrors.sol', NULL, '{}'::TEXT[]),
	('1b37f399', 'error', 'MainPrizeEarlyClaim', 'MainPrizeEarlyClaim(uint256,uint256)', 'CosmicSignatureErrors.sol', 'Not enough time has elapsed.', ARRAY['Not enough time has elapsed.']::TEXT[]),
	('afefe808', 'error', 'NftHasAlreadyBeenStaked', 'NftHasAlreadyBeenStaked(string,uint256)', 'CosmicSignatureErrors.sol', 'This NFT has already been staked in the past. An NFT is allowed to be staked only once.', ARRAY['This NFT has already been staked in the past. An NFT is allowed to be staked only once.']::TEXT[]),
	('91594fde', 'error', 'NftStakeActionAccessDenied', 'NftStakeActionAccessDenied(string,uint256,address)', 'CosmicSignatureErrors.sol', 'Only NFT owner is permitted to unstake it.', ARRAY['Only NFT owner is permitted to unstake it.']::TEXT[]),
	('08f7dac4', 'error', 'NftStakeActionInvalidId', 'NftStakeActionInvalidId(string,uint256)', 'CosmicSignatureErrors.sol', 'Invalid NFT stake action ID.', ARRAY['Invalid NFT stake action ID.']::TEXT[]),
	('c6c08d72', 'error', 'NoBidsPlacedInCurrentRound', 'NoBidsPlacedInCurrentRound()', 'CosmicSignatureErrors.sol', 'There have been no bids in the current bidding round yet.', ARRAY['There have been no bids in the current bidding round yet.']::TEXT[]),
	('d6234725', 'error', 'NotImplemented', 'NotImplemented()', 'CosmicSignatureErrors.sol', NULL, '{}'::TEXT[]),
	('be20b6ab', 'error', 'RoundIsActive', 'RoundIsActive(uint256,uint256)', 'CosmicSignatureErrors.sol', 'The current bidding round is already active.', ARRAY['The current bidding round is already active.']::TEXT[]),
	('51e3d86a', 'error', 'RoundIsInactive', 'RoundIsInactive(uint256,uint256)', 'CosmicSignatureErrors.sol', 'The current bidding round is not active yet.', ARRAY['The current bidding round is not active yet.']::TEXT[]),
	('eb8b1fd0', 'error', 'ThereAreStakedNfts', 'ThereAreStakedNfts(string)', 'CosmicSignatureErrors.sol', 'There are still staked NFTs.', ARRAY['There are still staked NFTs.']::TEXT[]),
	('48b0a7ea', 'error', 'TooLongBidMessage', 'TooLongBidMessage(uint256)', 'CosmicSignatureErrors.sol', 'Message is too long.', ARRAY['Message is too long.']::TEXT[]),
	('c2376851', 'error', 'TooLongNftName', 'TooLongNftName(string,uint256)', 'CosmicSignatureErrors.sol', 'NFT name is too long.', ARRAY['NFT name is too long.']::TEXT[]),
	('ced50f67', 'error', 'UnauthorizedCaller', 'UnauthorizedCaller(string,address)', 'CosmicSignatureErrors.sol', 'Deployer only.', ARRAY['Deployer only.','Only the CosmicSignatureGame contract is permitted to call this method.','Only the tresurer is permitted to call this method.']::TEXT[]),
	('729851a5', 'error', 'UsedRandomWalkNft', 'UsedRandomWalkNft(uint256)', 'CosmicSignatureErrors.sol', NULL, '{}'::TEXT[]),
	('eeb745ea', 'error', 'WrongBidType', 'WrongBidType()', 'CosmicSignatureErrors.sol', 'The first bid in a bidding round shall be ETH.', ARRAY['The first bid in a bidding round shall be ETH.']::TEXT[]),
	('eac0d389', 'error', 'ZeroAddress', 'ZeroAddress(string)', 'CosmicSignatureErrors.sol', 'Charity address not set.', ARRAY['Charity address not set.','The provided address is zero.']::TEXT[]),
	('20bc709aa4eb4e8757a663b1feadf4235acb2418a324a7348a84a1c166fb33b1', 'event', 'ArbGasInfoGetGasBacklogCallFailed', 'ArbGasInfoGetGasBacklogCallFailed()', 'ArbitrumHelpers.sol', 'ArbGasInfo.getGasBacklog call failed.', ARRAY['ArbGasInfo.getGasBacklog call failed.']::TEXT[]),
	('1031a98235b5d0b884fa4bb491d313b7c3add94719cc953bfce9c24abd651791', 'event', 'ArbGasInfoGetL1PricingUnitsSinceUpdateCallFailed', 'ArbGasInfoGetL1PricingUnitsSinceUpdateCallFailed()', 'ArbitrumHelpers.sol', 'ArbGasInfo.getL1PricingUnitsSinceUpdate call failed.', ARRAY['ArbGasInfo.getL1PricingUnitsSinceUpdate call failed.']::TEXT[]),
	('de09184d78b110c5942196171c5b8b344f399922de2be886f56a74ab1337041f', 'event', 'ArbSysArbBlockHashCallFailed', 'ArbSysArbBlockHashCallFailed()', 'ArbitrumHelpers.sol', 'ArbSys.arbBlockHash call failed.', ARRAY['ArbSys.arbBlockHash call failed.']::TEXT[]),
	('a8d743ae81d09947502807f411c542b10b60869063c5cb96a4024bfdaccff811', 'event', 'ArbSysArbBlockNumberCallFailed', 'ArbSysArbBlockNumberCallFailed()', 'ArbitrumHelpers.sol', 'ArbSys.arbBlockNumber call failed.', ARRAY['ArbSys.arbBlockNumber call failed.']::TEXT[]),
	('a0f59128cf0144d4891de440cb7fffc98340af3ee8b041d4add05fc0248c392d', 'event', 'ArbitrumError', 'ArbitrumError(string)', 'CosmicSignatureEvents.sol (pre-V3.1)', 'ArbSys.arbBlockNumber call failed.', ARRAY['ArbSys.arbBlockNumber call failed.','ArbSys.arbBlockHash call failed.','ArbGasInfo.getGasBacklog call failed.','ArbGasInfo.getL1PricingUnitsSinceUpdate call failed.']::TEXT[]),
	('f7fce645f12ae266a329c431e96ebea892316a1415809056621ffeea04efd4ab', 'event', 'ERC20TransferFailed', 'ERC20TransferFailed(string,address,uint256)', 'CosmicSignatureErrors.sol (pre-V3)', NULL, '{}'::TEXT[]),
	('1b957971c8e544b85ea06a7b3245ce66c403427f5885d4e49009a93a1c6c6348', 'event', 'EthTransferToCharityFailed', 'EthTransferToCharityFailed(address,uint256)', 'CosmicSignatureEvents.sol', 'ETH transfer to charity failed.', ARRAY['ETH transfer to charity failed.']::TEXT[]),
	('154fb6c686c977314af35b730a16b83facda5265b2abec7237c730f63e42215a', 'event', 'FundTransferFailed', 'FundTransferFailed(string,address,uint256)', 'CosmicSignatureEvents.sol', 'ETH transfer to charity failed.', ARRAY['ETH transfer to charity failed.']::TEXT[]);

-- ERC-721 approvals on the Cosmic Signature NFT.
CREATE TABLE cg_nft_approval ( -- IERC721.sol:Approval (CosmicSignatureNft)
	id				BIGSERIAL PRIMARY KEY,
	evtlog_id		BIGINT REFERENCES evt_log(id) ON DELETE CASCADE,
	block_num		BIGINT NOT NULL,
	tx_id			BIGINT NOT NULL,
	time_stamp		TIMESTAMPTZ NOT NULL,
	contract_aid	BIGINT NOT NULL,
	owner_aid		BIGINT NOT NULL,
	approved_aid	BIGINT NOT NULL,		-- zero address clears the approval
	token_id		BIGINT NOT NULL,
	UNIQUE(evtlog_id)
);
CREATE INDEX cg_nft_approval_token_idx ON cg_nft_approval(token_id, block_num DESC);
CREATE TABLE cg_nft_approval_for_all ( -- IERC721.sol:ApprovalForAll (CosmicSignatureNft)
	id				BIGSERIAL PRIMARY KEY,
	evtlog_id		BIGINT REFERENCES evt_log(id) ON DELETE CASCADE,
	block_num		BIGINT NOT NULL,
	tx_id			BIGINT NOT NULL,
	time_stamp		TIMESTAMPTZ NOT NULL,
	contract_aid	BIGINT NOT NULL,
	owner_aid		BIGINT NOT NULL,
	operator_aid	BIGINT NOT NULL,
	approved		BOOLEAN NOT NULL,
	UNIQUE(evtlog_id)
);
CREATE INDEX cg_nft_approval_for_all_owner_idx ON cg_nft_approval_for_all(owner_aid, block_num DESC);

-- ERC-20 approvals and ERC-20 Votes delegation on the CosmicToken.
CREATE TABLE cg_token_approval ( -- IERC20.sol:Approval (CosmicSignatureToken)
	id				BIGSERIAL PRIMARY KEY,
	evtlog_id		BIGINT REFERENCES evt_log(id) ON DELETE CASCADE,
	block_num		BIGINT NOT NULL,
	tx_id			BIGINT NOT NULL,
	time_stamp		TIMESTAMPTZ NOT NULL,
	contract_aid	BIGINT NOT NULL,
	owner_aid		BIGINT NOT NULL,
	spender_aid		BIGINT NOT NULL,
	value			DECIMAL NOT NULL,
	UNIQUE(evtlog_id)
);
CREATE INDEX cg_token_approval_owner_idx ON cg_token_approval(owner_aid, block_num DESC);
CREATE TABLE cg_token_delegate_changed ( -- IVotes.sol:DelegateChanged (CosmicSignatureToken)
	id					BIGSERIAL PRIMARY KEY,
	evtlog_id			BIGINT REFERENCES evt_log(id) ON DELETE CASCADE,
	block_num			BIGINT NOT NULL,
	tx_id				BIGINT NOT NULL,
	time_stamp			TIMESTAMPTZ NOT NULL,
	contract_aid		BIGINT NOT NULL,
	delegator_aid		BIGINT NOT NULL,
	from_delegate_aid	BIGINT NOT NULL,
	to_delegate_aid		BIGINT NOT NULL,
	UNIQUE(evtlog_id)
);
CREATE INDEX cg_token_delegate_changed_delegator_idx ON cg_token_delegate_changed(delegator_aid, block_num DESC);
CREATE TABLE cg_token_delegate_votes_changed ( -- IVotes.sol:DelegateVotesChanged (CosmicSignatureToken)
	id				BIGSERIAL PRIMARY KEY,
	evtlog_id		BIGINT REFERENCES evt_log(id) ON DELETE CASCADE,
	block_num		BIGINT NOT NULL,
	tx_id			BIGINT NOT NULL,
	time_stamp		TIMESTAMPTZ NOT NULL,
	contract_aid	BIGINT NOT NULL,
	delegate_aid	BIGINT NOT NULL,
	previous_votes	DECIMAL NOT NULL,
	new_votes		DECIMAL NOT NULL,
	UNIQUE(evtlog_id)
);
CREATE INDEX cg_token_delegate_votes_changed_delegate_idx ON cg_token_delegate_votes_changed(delegate_aid, block_num DESC);
CREATE TABLE cg_eip712_domain_changed ( -- IERC5267.sol:EIP712DomainChanged (CosmicSignatureToken, CosmicSignatureDao)
	id				BIGSERIAL PRIMARY KEY,
	evtlog_id		BIGINT REFERENCES evt_log(id) ON DELETE CASCADE,
	block_num		BIGINT NOT NULL,
	tx_id			BIGINT NOT NULL,
	time_stamp		TIMESTAMPTZ NOT NULL,
	contract_aid	BIGINT NOT NULL,
	UNIQUE(evtlog_id)
);

-- CosmicSignatureDao (OpenZeppelin Governor).
CREATE TABLE cg_dao_proposal_created ( -- IGovernor.sol:ProposalCreated
	id				BIGSERIAL PRIMARY KEY,
	evtlog_id		BIGINT REFERENCES evt_log(id) ON DELETE CASCADE,
	block_num		BIGINT NOT NULL,
	tx_id			BIGINT NOT NULL,
	time_stamp		TIMESTAMPTZ NOT NULL,
	contract_aid	BIGINT NOT NULL,
	proposal_id		DECIMAL NOT NULL,		-- uint256 proposal hash
	proposer_aid	BIGINT NOT NULL,
	targets			TEXT[] NOT NULL,		-- call batch, kept verbatim
	call_values		DECIMAL[] NOT NULL,		-- msg.value per target
	signatures		TEXT[] NOT NULL,
	calldatas		BYTEA[] NOT NULL,
	vote_start		BIGINT NOT NULL,		-- timepoint (block number or timestamp per the token clock)
	vote_end		BIGINT NOT NULL,
	description		TEXT NOT NULL,
	UNIQUE(evtlog_id)
);
CREATE INDEX cg_dao_proposal_created_pid_idx ON cg_dao_proposal_created(proposal_id);
CREATE TABLE cg_dao_proposal_state ( -- IGovernor.sol:ProposalQueued / ProposalExecuted / ProposalCanceled
	id				BIGSERIAL PRIMARY KEY,
	evtlog_id		BIGINT REFERENCES evt_log(id) ON DELETE CASCADE,
	block_num		BIGINT NOT NULL,
	tx_id			BIGINT NOT NULL,
	time_stamp		TIMESTAMPTZ NOT NULL,
	contract_aid	BIGINT NOT NULL,
	proposal_id		DECIMAL NOT NULL,
	state			SMALLINT NOT NULL,		-- 1 queued, 2 executed, 3 canceled
	eta_seconds		BIGINT,					-- ProposalQueued only
	UNIQUE(evtlog_id)
);
CREATE INDEX cg_dao_proposal_state_pid_idx ON cg_dao_proposal_state(proposal_id, block_num DESC);
CREATE TABLE cg_dao_vote_cast ( -- IGovernor.sol:VoteCast / VoteCastWithParams
	id				BIGSERIAL PRIMARY KEY,
	evtlog_id		BIGINT REFERENCES evt_log(id) ON DELETE CASCADE,
	block_num		BIGINT NOT NULL,
	tx_id			BIGINT NOT NULL,
	time_stamp		TIMESTAMPTZ NOT NULL,
	contract_aid	BIGINT NOT NULL,
	voter_aid		BIGINT NOT NULL,
	proposal_id		DECIMAL NOT NULL,
	support			SMALLINT NOT NULL,		-- GovernorCountingSimple: 0 against, 1 for, 2 abstain
	weight			DECIMAL NOT NULL,
	reason			TEXT NOT NULL,
	params			BYTEA,					-- VoteCastWithParams only
	UNIQUE(evtlog_id)
);
CREATE INDEX cg_dao_vote_cast_pid_idx ON cg_dao_vote_cast(proposal_id, block_num DESC);
CREATE INDEX cg_dao_vote_cast_voter_idx ON cg_dao_vote_cast(voter_aid, block_num DESC);
CREATE TABLE cg_dao_setting_changed ( -- GovernorSettings.sol:ProposalThresholdSet/VotingDelaySet/VotingPeriodSet, GovernorVotesQuorumFraction.sol:QuorumNumeratorUpdated
	id				BIGSERIAL PRIMARY KEY,
	evtlog_id		BIGINT REFERENCES evt_log(id) ON DELETE CASCADE,
	block_num		BIGINT NOT NULL,
	tx_id			BIGINT NOT NULL,
	time_stamp		TIMESTAMPTZ NOT NULL,
	contract_aid	BIGINT NOT NULL,
	setting			SMALLINT NOT NULL,		-- 1 proposal threshold, 2 voting delay, 3 voting period, 4 quorum numerator
	old_value		DECIMAL NOT NULL,
	new_value		DECIMAL NOT NULL,
	UNIQUE(evtlog_id)
);

-- +goose Down
DROP TABLE cg_dao_setting_changed;
DROP TABLE cg_dao_vote_cast;
DROP TABLE cg_dao_proposal_state;
DROP TABLE cg_dao_proposal_created;
DROP TABLE cg_eip712_domain_changed;
DROP TABLE cg_token_delegate_votes_changed;
DROP TABLE cg_token_delegate_changed;
DROP TABLE cg_token_approval;
DROP TABLE cg_nft_approval_for_all;
DROP TABLE cg_nft_approval;
DROP TABLE cg_error_lookup;

-- Restore the trigger body from migration 00002.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION on_eth_deposit_insert() RETURNS trigger AS  $$
DECLARE
	v_amount_per_token DECIMAL;
	v_mod DECIMAL;
	v_rec RECORD;
	v_cnt						NUMERIC;
	v_prev_num_tokens		INT;
	v_prev_amount			DECIMAL;
	v_prev_amount_per_token	DECIMAL;
	v_tokens_added			INT;
BEGIN

	IF NEW.num_staked_nfts > 0 THEN
		SELECT accumulated_nfts,accumulated_amount,accumulated_per_token FROM cg_staking_eth_deposit ORDER BY deposit_id DESC OFFSET 1 LIMIT 1 INTO v_prev_num_tokens,v_prev_amount,v_prev_amount_per_token;
		IF v_prev_num_tokens IS NULL THEN
			v_prev_num_tokens:=0;
			v_tokens_added:=NEW.num_staked_nfts;
		ELSE
			v_tokens_added:=NEW.num_staked_nfts-v_prev_num_tokens;
		END IF;
		IF v_prev_amount IS NULL THEN
			v_prev_amount:=0;
		END IF;
		v_mod := MOD(NEW.deposit_amount,NEW.num_staked_nfts);
		v_amount_per_token := (NEW.deposit_amount - v_mod) / NEW.num_staked_nfts;
		UPDATE cg_staker_cst
			SET total_reward = (total_reward + (v_amount_per_token*total_tokens_staked)),
				unclaimed_reward = (unclaimed_reward + (v_amount_per_token*total_tokens_staked))
			WHERE total_tokens_staked > 0;
		UPDATE cg_stake_stats_cst
			SET
				total_reward_amount = (total_reward_amount + (NEW.deposit_amount - v_mod)),
				total_unclaimed_reward = (total_unclaimed_reward + (NEW.deposit_amount - v_mod)),
				num_deposits = (num_deposits + 1),
				total_modulo = (total_modulo + v_mod)
			;
		FOR v_rec IN (SELECT count(*) AS num_toks,staker_aid FROM cg_staked_token_cst GROUP BY staker_aid)
		LOOP
			INSERT INTO cg_staker_deposit(staker_aid,deposit_id,tokens_staked,amount_to_claim,amount_deposited)
				VALUES(v_rec.staker_aid,NEW.deposit_id,v_rec.num_toks,v_amount_per_token*v_rec.num_toks,v_amount_per_token*v_rec.num_toks);
		END LOOP;
		FOR v_rec IN (SELECT token_id,stake_action_id,staker_aid FROM cg_staked_token_cst)
		LOOP
			UPDATE cg_staked_token_cst_rewards 
				SET accumulated_reward = (accumulated_reward + v_amount_per_token)
				WHERE stake_action_id=v_rec.stake_action_id;
			GET DIAGNOSTICS v_cnt = ROW_COUNT;
			IF v_cnt = 0 THEN
				INSERT INTO cg_staked_token_cst_rewards(staker_aid,token_id,stake_action_id,accumulated_reward)
					VALUES(v_rec.staker_aid,v_rec.token_id,v_rec.stake_action_id,v_amount_per_token);
			END IF;
			INSERT INTO cg_st_reward(staker_aid,action_id,token_id,deposit_id,round_num,reward)
				VALUES(v_rec.staker_aid,v_rec.stake_action_id,v_rec.token_id,NEW.deposit_id,NEW.round_num,v_amount_per_token);
		END LOOP;
		UPDATE cg_staking_eth_deposit 
			SET 
				
				accumulated_amount = (v_prev_amount + NEW.deposit_amount),
				accumulated_per_token = (v_prev_amount_per_token + v_amount_per_token),
				accumulated_nfts = num_staked_nfts,
				num_staked_nfts = v_tokens_added
			WHERE id=NEW.id;
	END IF;

	-- Insert record in cg_prize table with ptype=15 for Staking Deposit ETH (for CS NFT stakers)
	-- Using winner_index=0 to indicate this is a general staking reward, not a specific winner's prize
	INSERT INTO cg_prize(round_num,winner_index,ptype) VALUES(NEW.round_num,0,15);

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

ALTER TABLE cg_staking_eth_deposit DROP COLUMN reward_per_staked_nft;
ALTER TABLE cg_nft_unstaked_rwalk DROP COLUMN action_counter;
ALTER TABLE cg_fund_transf_err DROP COLUMN err_str;
