//go:build go1.22

// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BidType.
const (
	Cst        BidType = "cst"
	Eth        BidType = "eth"
	RandomWalk BidType = "randomWalk"
	Unknown    BidType = "unknown"
)

// Valid indicates whether the value is a known member of the BidType enum.
func (e BidType) Valid() bool {
	switch e {
	case Cst:
		return true
	case Eth:
		return true
	case RandomWalk:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for RoundStatus.
const (
	Completed RoundStatus = "completed"
	Open      RoundStatus = "open"
)

// Valid indicates whether the value is a known member of the RoundStatus enum.
func (e RoundStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Bid defines model for Bid.
type Bid struct {
	BidCstRewardAmountWei          *string        `json:"bidCstRewardAmountWei,omitempty"`
	BidType                        BidType        `json:"bidType"`
	BidderAddress                  string         `json:"bidderAddress"`
	BlockNumber                    int64          `json:"blockNumber"`
	CstDutchAuctionDurationSeconds *int64         `json:"cstDutchAuctionDurationSeconds,omitempty"`
	CstPriceWei                    *string        `json:"cstPriceWei,omitempty"`
	CstRewardWei                   string         `json:"cstRewardWei"`
	Erc20Donation                  *Erc20Donation `json:"erc20Donation,omitempty"`
	EthPriceWei                    *string        `json:"ethPriceWei,omitempty"`
	EventLogId                     int64          `json:"eventLogId"`
	Message                        *string        `json:"message,omitempty"`
	NftDonation                    *NftDonation   `json:"nftDonation,omitempty"`
	OccurredAt                     time.Time      `json:"occurredAt"`
	Position                       int64          `json:"position"`
	PrizeAt                        time.Time      `json:"prizeAt"`
	RandomWalkTokenId              *int64         `json:"randomWalkTokenId,omitempty"`
	Round                          int64          `json:"round"`
	TransactionHash                string         `json:"transactionHash"`
}

// BidType defines model for BidType.
type BidType string

// CharityAllocation defines model for CharityAllocation.
type CharityAllocation struct {
	AmountWei        string   `json:"amountWei"`
	CharityAddresses []string `json:"charityAddresses"`
}

// ChronoWarriorPrize defines model for ChronoWarriorPrize.
type ChronoWarriorPrize struct {
	CstAmountWei  string `json:"cstAmountWei"`
	EthAmountWei  string `json:"ethAmountWei"`
	NftTokenId    int64  `json:"nftTokenId"`
	WinnerAddress string `json:"winnerAddress"`
}

// ClaimTransaction defines model for ClaimTransaction.
type ClaimTransaction struct {
	BlockNumber     int64     `json:"blockNumber"`
	EventLogId      int64     `json:"eventLogId"`
	OccurredAt      time.Time `json:"occurredAt"`
	TransactionHash string    `json:"transactionHash"`
}

// CosmicGameCurrentRound defines model for CosmicGameCurrentRound.
type CosmicGameCurrentRound struct {
	LastBidderAddress                  *string         `json:"lastBidderAddress,omitempty"`
	MainPrizeAmountWei                 string          `json:"mainPrizeAmountWei"`
	MainPrizeTimeIncrementMicroseconds string          `json:"mainPrizeTimeIncrementMicroseconds"`
	NextEthBidPriceWei                 string          `json:"nextEthBidPriceWei"`
	RafflePrizeAmountWei               string          `json:"rafflePrizeAmountWei"`
	Round                              int64           `json:"round"`
	SecondsUntilMainPrize              int64           `json:"secondsUntilMainPrize"`
	StakingRewardAmountWei             string          `json:"stakingRewardAmountWei"`
	Statistics                         RoundStatistics `json:"statistics"`
	Status                             RoundStatus     `json:"status"`
}

// CosmicGameRound defines model for CosmicGameRound.
type CosmicGameRound struct {
	Charity           *CharityAllocation  `json:"charity,omitempty"`
	ChronoWarrior     *ChronoWarriorPrize `json:"chronoWarrior,omitempty"`
	Claim             ClaimTransaction    `json:"claim"`
	EnduranceChampion *TokenPrize         `json:"enduranceChampion,omitempty"`
	LastCstBidder     *TokenPrize         `json:"lastCstBidder,omitempty"`
	MainPrize         MainPrize           `json:"mainPrize"`
	Round             int64               `json:"round"`
	Staking           *StakingAllocation  `json:"staking,omitempty"`
	Statistics        RoundStatistics     `json:"statistics"`
	Status            RoundStatus         `json:"status"`
}

// CosmicGameRoundSummary defines model for CosmicGameRoundSummary.
type CosmicGameRoundSummary struct {
	CompletedAt          time.Time   `json:"completedAt"`
	DonatedNftCount      int64       `json:"donatedNftCount"`
	Erc20DonationCount   int64       `json:"erc20DonationCount"`
	MainPrize            MainPrize   `json:"mainPrize"`
	RaffleEthDepositsWei string      `json:"raffleEthDepositsWei"`
	RaffleNftCount       int64       `json:"raffleNftCount"`
	Round                int64       `json:"round"`
	Status               RoundStatus `json:"status"`
	TotalBids            int64       `json:"totalBids"`
}

// Erc20Donation defines model for Erc20Donation.
type Erc20Donation struct {
	AmountWei    string `json:"amountWei"`
	TokenAddress string `json:"tokenAddress"`
}

// MainPrize defines model for MainPrize.
type MainPrize struct {
	CstAmountWei                *string    `json:"cstAmountWei,omitempty"`
	EthAmountWei                string     `json:"ethAmountWei"`
	NftTokenId                  int64      `json:"nftTokenId"`
	SecondaryPrizeClaimDeadline *time.Time `json:"secondaryPrizeClaimDeadline,omitempty"`
	Seed                        *string    `json:"seed,omitempty"`
	WinnerAddress               string     `json:"winnerAddress"`
}

// NftDonation defines model for NftDonation.
type NftDonation struct {
	TokenAddress string `json:"tokenAddress"`
	TokenId      int64  `json:"tokenId"`
	TokenUri     string `json:"tokenUri"`
}

// PageMeta defines model for PageMeta.
type PageMeta struct {
	Limit      int     `json:"limit"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// RoundBidPage defines model for RoundBidPage.
type RoundBidPage struct {
	Data []Bid    `json:"data"`
	Meta PageMeta `json:"meta"`
}

// RoundPage defines model for RoundPage.
type RoundPage struct {
	Data []CosmicGameRoundSummary `json:"data"`
	Meta PageMeta                 `json:"meta"`
}

// RoundStatistics defines model for RoundStatistics.
type RoundStatistics struct {
	ActivatedAt                    *time.Time `json:"activatedAt,omitempty"`
	DonatedNftCount                int64      `json:"donatedNftCount"`
	DonationAmountWei              string     `json:"donationAmountWei"`
	DonationCount                  int64      `json:"donationCount"`
	Erc20DonationCount             int64      `json:"erc20DonationCount"`
	ParameterWindowDurationSeconds *int64     `json:"parameterWindowDurationSeconds,omitempty"`
	ParameterWindowStartedAt       *time.Time `json:"parameterWindowStartedAt,omitempty"`
	RaffleEthDepositsWei           string     `json:"raffleEthDepositsWei"`
	RaffleNftCount                 int64      `json:"raffleNftCount"`
	RoundDurationSeconds           *int64     `json:"roundDurationSeconds,omitempty"`
	RoundEndedAt                   *time.Time `json:"roundEndedAt,omitempty"`
	RoundStartedAt                 *time.Time `json:"roundStartedAt,omitempty"`
	TotalBids                      int64      `json:"totalBids"`
}

// RoundStatus defines model for RoundStatus.
type RoundStatus string

// StakingAllocation defines model for StakingAllocation.
type StakingAllocation struct {
	AmountPerTokenWei string `json:"amountPerTokenWei"`
	AmountWei         string `json:"amountWei"`
	DepositId         int64  `json:"depositId"`
	StakedTokenCount  int64  `json:"stakedTokenCount"`
}

// TokenPrize defines model for TokenPrize.
type TokenPrize struct {
	CstAmountWei  string `json:"cstAmountWei"`
	NftTokenId    int64  `json:"nftTokenId"`
	WinnerAddress string `json:"winnerAddress"`
}

// BidPosition defines model for BidPosition.
type BidPosition = int64

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// Round defines model for Round.
type Round = int64

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// InternalError defines model for InternalError.
type InternalError = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Problem

// ListRoundsParams defines parameters for ListRounds.
type ListRoundsParams struct {
	// Cursor Opaque continuation cursor returned by the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of resources to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRoundBidsParams defines parameters for ListRoundBids.
type ListRoundBidsParams struct {
	// Cursor Opaque continuation cursor returned by the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of resources to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List completed CosmicGame rounds
	// (GET /api/v2/cosmicgame/rounds)
	ListRounds(w http.ResponseWriter, r *http.Request, params ListRoundsParams)
	// Get the current open CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/current)
	GetCurrentRound(w http.ResponseWriter, r *http.Request)
	// Get one completed CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round})
	GetRound(w http.ResponseWriter, r *http.Request, round Round)
	// List bids in one CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round}/bids)
	ListRoundBids(w http.ResponseWriter, r *http.Request, round Round, params ListRoundBidsParams)
	// Get one bid by its position in a CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round}/bids/{position})
	GetRoundBid(w http.ResponseWriter, r *http.Request, round Round, position BidPosition)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListRounds operation middleware
func (siw *ServerInterfaceWrapper) ListRounds(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRoundsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRounds(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentRound operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentRound(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentRound(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRound operation middleware
func (siw *ServerInterfaceWrapper) GetRound(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "round" -------------
	var round Round

	err = runtime.BindStyledParameterWithOptions("simple", "round", r.PathValue("round"), &round, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "round", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRound(w, r, round)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoundBids operation middleware
func (siw *ServerInterfaceWrapper) ListRoundBids(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "round" -------------
	var round Round

	err = runtime.BindStyledParameterWithOptions("simple", "round", r.PathValue("round"), &round, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "round", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRoundBidsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoundBids(w, r, round, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoundBid operation middleware
func (siw *ServerInterfaceWrapper) GetRoundBid(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "round" -------------
	var round Round

	err = runtime.BindStyledParameterWithOptions("simple", "round", r.PathValue("round"), &round, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "round", Err: err})
		return
	}

	// ------------- Path parameter "position" -------------
	var position BidPosition

	err = runtime.BindStyledParameterWithOptions("simple", "position", r.PathValue("position"), &position, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "position", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoundBid(w, r, round, position)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds", wrapper.ListRounds)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/current", wrapper.GetCurrentRound)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/{round}", wrapper.GetRound)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/{round}/bids", wrapper.ListRoundBids)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/{round}/bids/{position}", wrapper.GetRoundBid)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type BidJSONResponse Bid

type CosmicGameCurrentRoundJSONResponse CosmicGameCurrentRound

type CosmicGameRoundJSONResponse CosmicGameRound

type InternalErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type RoundBidPageJSONResponse RoundBidPage

type RoundPageJSONResponse RoundPage

type ServiceUnavailableResponseHeaders struct {
	RetryAfter int
}
type ServiceUnavailableApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ServiceUnavailableResponseHeaders
}

type ListRoundsRequestObject struct {
	Params ListRoundsParams
}

type ListRoundsResponseObject interface {
	VisitListRoundsResponse(w http.ResponseWriter) error
}

type ListRounds200JSONResponse struct{ RoundPageJSONResponse }

func (response ListRounds200JSONResponse) VisitListRoundsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRounds400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListRounds400ApplicationProblemPlusJSONResponse) VisitListRoundsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListRounds500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListRounds500ApplicationProblemPlusJSONResponse) VisitListRoundsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentRoundRequestObject struct {
}

type GetCurrentRoundResponseObject interface {
	VisitGetCurrentRoundResponse(w http.ResponseWriter) error
}

type GetCurrentRound200JSONResponse struct {
	CosmicGameCurrentRoundJSONResponse
}

func (response GetCurrentRound200JSONResponse) VisitGetCurrentRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentRound500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetCurrentRound500ApplicationProblemPlusJSONResponse) VisitGetCurrentRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentRound503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response GetCurrentRound503ApplicationProblemPlusJSONResponse) VisitGetCurrentRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoundRequestObject struct {
	Round Round `json:"round"`
}

type GetRoundResponseObject interface {
	VisitGetRoundResponse(w http.ResponseWriter) error
}

type GetRound200JSONResponse struct{ CosmicGameRoundJSONResponse }

func (response GetRound200JSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRound400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetRound400ApplicationProblemPlusJSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRound404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetRound404ApplicationProblemPlusJSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRound500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetRound500ApplicationProblemPlusJSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundBidsRequestObject struct {
	Round  Round `json:"round"`
	Params ListRoundBidsParams
}

type ListRoundBidsResponseObject interface {
	VisitListRoundBidsResponse(w http.ResponseWriter) error
}

type ListRoundBids200JSONResponse struct{ RoundBidPageJSONResponse }

func (response ListRoundBids200JSONResponse) VisitListRoundBidsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundBids400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListRoundBids400ApplicationProblemPlusJSONResponse) VisitListRoundBidsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundBids500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListRoundBids500ApplicationProblemPlusJSONResponse) VisitListRoundBidsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoundBidRequestObject struct {
	Round    Round       `json:"round"`
	Position BidPosition `json:"position"`
}

type GetRoundBidResponseObject interface {
	VisitGetRoundBidResponse(w http.ResponseWriter) error
}

type GetRoundBid200JSONResponse struct{ BidJSONResponse }

func (response GetRoundBid200JSONResponse) VisitGetRoundBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoundBid400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetRoundBid400ApplicationProblemPlusJSONResponse) VisitGetRoundBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoundBid404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetRoundBid404ApplicationProblemPlusJSONResponse) VisitGetRoundBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoundBid500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetRoundBid500ApplicationProblemPlusJSONResponse) VisitGetRoundBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List completed CosmicGame rounds
	// (GET /api/v2/cosmicgame/rounds)
	ListRounds(ctx context.Context, request ListRoundsRequestObject) (ListRoundsResponseObject, error)
	// Get the current open CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/current)
	GetCurrentRound(ctx context.Context, request GetCurrentRoundRequestObject) (GetCurrentRoundResponseObject, error)
	// Get one completed CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round})
	GetRound(ctx context.Context, request GetRoundRequestObject) (GetRoundResponseObject, error)
	// List bids in one CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round}/bids)
	ListRoundBids(ctx context.Context, request ListRoundBidsRequestObject) (ListRoundBidsResponseObject, error)
	// Get one bid by its position in a CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round}/bids/{position})
	GetRoundBid(ctx context.Context, request GetRoundBidRequestObject) (GetRoundBidResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListRounds operation middleware
func (sh *strictHandler) ListRounds(w http.ResponseWriter, r *http.Request, params ListRoundsParams) {
	var request ListRoundsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRounds(ctx, request.(ListRoundsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRounds")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRoundsResponseObject); ok {
		if err := validResponse.VisitListRoundsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentRound operation middleware
func (sh *strictHandler) GetCurrentRound(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentRoundRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentRound(ctx, request.(GetCurrentRoundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentRound")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentRoundResponseObject); ok {
		if err := validResponse.VisitGetCurrentRoundResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRound operation middleware
func (sh *strictHandler) GetRound(w http.ResponseWriter, r *http.Request, round Round) {
	var request GetRoundRequestObject

	request.Round = round

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRound(ctx, request.(GetRoundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRound")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRoundResponseObject); ok {
		if err := validResponse.VisitGetRoundResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRoundBids operation middleware
func (sh *strictHandler) ListRoundBids(w http.ResponseWriter, r *http.Request, round Round, params ListRoundBidsParams) {
	var request ListRoundBidsRequestObject

	request.Round = round
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRoundBids(ctx, request.(ListRoundBidsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRoundBids")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRoundBidsResponseObject); ok {
		if err := validResponse.VisitListRoundBidsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRoundBid operation middleware
func (sh *strictHandler) GetRoundBid(w http.ResponseWriter, r *http.Request, round Round, position BidPosition) {
	var request GetRoundBidRequestObject

	request.Round = round
	request.Position = position

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRoundBid(ctx, request.(GetRoundBidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRoundBid")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRoundBidResponseObject); ok {
		if err := validResponse.VisitGetRoundBidResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FtbTyM5Fv4rlnfepiAZmh6p8waB6UXqZhDQi7Q9rOSUTxIPVXb1sSuQQfnvK9uVuqVyqQow7D51h/hy",
	"/H3nap8801DFiZIgjaaDZ5owZDEYQPfpVPArpYURStqPHHSIIvEf6e8SDkZMAycjwUmSjSOPwkyFJGYK",
	"BFUq+SENqLDjE2amNKCSxWA/LdcNKMKPVCBwOjCYQkB1OIWY2Q3HCmNm6IAKaX49pgGNhRRxGtPBLwE1",
	"8wT8VzABpItFQIcpaoUNoibsRwokVNIImTInZ+jGEgSTorSHmDuZE4SZUKkmCZtALvuPFHBeCO/n0rKo",
	"MXv6AnJipnTw8ZcjJ+nycyGrNijkxIn6RcTCrEr6lT3ZAxKZxiNAosYEQasUQ9DEqEzadWJFbs2yVBzG",
	"LI0MHXzsB1ZED95Rv78VymvL3ap8/wZUGetDpWMRfmZxRnQm8xq+3ZCOZPcbJFzYpXSipAavqoxfw48U",
	"tAPVMg3S/ZclSSRCx3kvQTWKIP75T+0Vutj8J4QxHdB/9Apz6Plvde/Kz/KbVuE4IfaURCFxVJDcfIjQ",
	"RMgZiwQ/pIvAWtIGudrJY9dqkOXWWpyHwNuk27hgaZgigjQ5sS8iy5rl14gX+jFEJSAzpRmjip3hhSyc",
	"AieRmHlDRRYaog0zUDvHax1go+QFsHaNCOz/Mve2COiFNICSReeI3v28lf6VRCOhSiNOpDJkBIWUTr5L",
	"ZX7bgtprimaxyrwY4Qq0ExKehDZOOge8DTVsAi/Ga2XRBvF+l2C1axSB8/TO0zqFHAmuC7FeXqYWAtVU",
	"zYt1AzgTIXyTbMZEZMe/NavrLdV6PcttZufRnORC2rAwBcazzOIaDM4PTsYGGsL1DYRKck1SaUTknIOE",
	"J0OseDyNsq0P/I4IYwQ9PdwYWjbGOnfK7OhZ0uNg5NwlKCy6QpUAGmEDzZhFGgKalP70TEeCD7W5hkeG",
	"/CRWqTR3IHw2ZaxjoAP6n+/9g0/3P/9EV3KBwE6/dX/b6vbdMD+DA55wjqB1baP+k92KHYxPDn67fz7u",
	"L5r3jFT4cOkCduvYG9BQm7PUhNOTNLQQnaXo1C3jrduCVyhCaIVbuMS81SzA8Kh/piRbZrWbMD+vDLaz",
	"zbS9oDADab6oyQVvndQGNAatMye0srAcm11PclkaugioCp2N8hNTEYkzAwdGxNB0jKRUCrQ8RILiL2iz",
	"FzLJVXzHoodb9QByG3KNSoXLkNdynkEmNXOa/U+mpxvt69fjJvtalJ3R9zL/Vctb3avCTN3QgzyLLlVP",
	"S+9RgFyzjPtcPDX6E0KTpaNLlwPSAvHdajYt4+6XoQFN5YNUj7K0TkHTcMpQmPlJFKkwV8MWnpO195Zh",
	"tqXHxC8jDMTd/GD2B4bI5iu8rWwVlARugnU4RSXVHUMUCq8sHS3xCLXpEEDATDvMkmPT3bYehZT7RKAa",
	"0tXlaicKqrBUJG9kIWIivi0Mq2003ys07uXru3jld+OtGqlYW322ICRi2pzunfHETEhnkh1MJZ97K2K4",
	"kCFCDNJ8FSEqXeQ8O5odPJlzM7WlSetEAtl4HEHXU3SNh9kRv9ls/OsSiS7rGPYg5KRznmwTfqGNCPVO",
	"hdZNMTybnO4+MdUrdrGMvdlKjUyuA6tR/dbwuRaonfSwAtNmk+xii1lI3HqrspIXuMhdio7bV1gJpXYJ",
	"69q3Tq37f+uWJU+RyRCGUxYnO+TLLsDk+1oXNFx6oXZT47LFbJpWaMs+tupVZ9teN35YlZ/3Zl+e7DKC",
	"bZX7Jo1jhvO2Or68dmkThrktroBfjs3Q2muXzKFca3ZdpKO2OT90bqZn4CoL3SEq7XHyPZS9rc4F1CjD",
	"olPR4Zpiq76W9KaqtcWeq4rSSPwaSlawbrKB8/oFx+vWY8Z6uxcrBCqrbSu3KsnI/2OV5YM6w7k7pYtr",
	"Z8B4JCTs7pk0AG+8PXrbGm5L0XZZvcpqweaeCphpcCd+3MxvKBrgbdJrV1HVNDxfogmUKzaBr2BY24Jp",
	"+ba8+4uvz2aL9/O2z9nls/rtG8+TPSy0Ow4Hw0TUqMJCamOzugp3KYoDhDEg2G/WFBI+buQAffz0qQTQ",
	"cb+ZbmGi5otYk12m5e/tlI1UagajiMkHGuwsW11r/MWe3zeXuwnZ+htaG3iZV7D8Em3r23P92iygcaak",
	"G1+VlspcP6UTIFtj7dle+2BrMse/5aw3lUS8TfgOjZixN89ceea4O4RHvme++yJJc961cSckV4/7P2fV",
	"FrwxDFuS8h4y8v1xcMucS97y7JkNtMXsxTL7V0vX6/reZDobvYKPWssnm7zgoAFVCTQ/0ayW+l1KgitA",
	"l721UsMO1QT38F10vfsA7sTspvd1X53LUj5K0IBIw95NNJYuht6iYHnPDzwl2WrPO6vALVyiN1arjSLX",
	"WVfRgUIB0gAnJ1cXZKyQXOfvmITJcq/iIfnXkW/OM6h4GgL/Q4rlTSqLojl5nIoIXNfJGNVfIMnsl6LN",
	"BcHW9brU1/KHzDO0Ab2+G34mpyx8AOllmR3RgM4AtRe4f/jhsO9eehKQLBF0QD8c9g8/0MC1SzqgeywR",
	"vdlRL3QyT1gMPd/+Y7+cgFNrqxzOmC239IvQ/mFF06DSwfu9OUsphvSyjH8RbB3pG1YX97W+y6N+f10y",
	"lI8rNz4F9HiXGaV2zkVAP+4ypdqE55p6ltd/DqFSO1W9ddUVYmxiEaOr393btday0suanday8xlM5fGr",
	"C4Dr2iy7QWNnfdg+q6HTrIrqZzC+dbPc1lnHbx9on92/i03QLjFtp/YZfPf7cZGT0EGlj/vH26fkfZsv",
	"YQOWLSVhgxm8AFW9kdjFUWXJVSfSgvfk1PIO07/Rr1nIiZCO3N0odSS1ILT3vGw42m6Lp4K/HrPlH6R0",
	"Yy27wPifstiRcD9PEUYXP7MRkrCWbLu7YJwtOUkxogPao4v7xX8DAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
