//go:build go1.22

// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BidType.
const (
	Cst        BidType = "cst"
	Eth        BidType = "eth"
	RandomWalk BidType = "randomWalk"
	Unknown    BidType = "unknown"
)

// Valid indicates whether the value is a known member of the BidType enum.
func (e BidType) Valid() bool {
	switch e {
	case Cst:
		return true
	case Eth:
		return true
	case RandomWalk:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for RaffleNftPool.
const (
	Bidder           RaffleNftPool = "bidder"
	RandomWalkStaker RaffleNftPool = "randomWalkStaker"
)

// Valid indicates whether the value is a known member of the RaffleNftPool enum.
func (e RaffleNftPool) Valid() bool {
	switch e {
	case Bidder:
		return true
	case RandomWalkStaker:
		return true
	default:
		return false
	}
}

// Defines values for RoundPrizeType.
const (
	BidderRaffleCst           RoundPrizeType = "bidderRaffleCst"
	BidderRaffleEth           RoundPrizeType = "bidderRaffleEth"
	BidderRaffleNft           RoundPrizeType = "bidderRaffleNft"
	ChronoWarriorCst          RoundPrizeType = "chronoWarriorCst"
	ChronoWarriorEth          RoundPrizeType = "chronoWarriorEth"
	ChronoWarriorNft          RoundPrizeType = "chronoWarriorNft"
	CosmicSignatureStakingEth RoundPrizeType = "cosmicSignatureStakingEth"
	EnduranceChampionCst      RoundPrizeType = "enduranceChampionCst"
	EnduranceChampionNft      RoundPrizeType = "enduranceChampionNft"
	LastCstBidderCst          RoundPrizeType = "lastCstBidderCst"
	LastCstBidderNft          RoundPrizeType = "lastCstBidderNft"
	MainPrizeCst              RoundPrizeType = "mainPrizeCst"
	MainPrizeEth              RoundPrizeType = "mainPrizeEth"
	MainPrizeNft              RoundPrizeType = "mainPrizeNft"
	RandomWalkStakerRaffleCst RoundPrizeType = "randomWalkStakerRaffleCst"
	RandomWalkStakerRaffleNft RoundPrizeType = "randomWalkStakerRaffleNft"
)

// Valid indicates whether the value is a known member of the RoundPrizeType enum.
func (e RoundPrizeType) Valid() bool {
	switch e {
	case BidderRaffleCst:
		return true
	case BidderRaffleEth:
		return true
	case BidderRaffleNft:
		return true
	case ChronoWarriorCst:
		return true
	case ChronoWarriorEth:
		return true
	case ChronoWarriorNft:
		return true
	case CosmicSignatureStakingEth:
		return true
	case EnduranceChampionCst:
		return true
	case EnduranceChampionNft:
		return true
	case LastCstBidderCst:
		return true
	case LastCstBidderNft:
		return true
	case MainPrizeCst:
		return true
	case MainPrizeEth:
		return true
	case MainPrizeNft:
		return true
	case RandomWalkStakerRaffleCst:
		return true
	case RandomWalkStakerRaffleNft:
		return true
	default:
		return false
	}
}

// Defines values for RoundStatus.
const (
	Completed RoundStatus = "completed"
	Open      RoundStatus = "open"
)

// Valid indicates whether the value is a known member of the RoundStatus enum.
func (e RoundStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Bid defines model for Bid.
type Bid struct {
	BidCstRewardAmountWei          *string        `json:"bidCstRewardAmountWei,omitempty"`
	BidType                        BidType        `json:"bidType"`
	BidderAddress                  string         `json:"bidderAddress"`
	BlockNumber                    int64          `json:"blockNumber"`
	CstDutchAuctionDurationSeconds *int64         `json:"cstDutchAuctionDurationSeconds,omitempty"`
	CstPriceWei                    *string        `json:"cstPriceWei,omitempty"`
	CstRewardWei                   string         `json:"cstRewardWei"`
	Erc20Donation                  *Erc20Donation `json:"erc20Donation,omitempty"`
	EthPriceWei                    *string        `json:"ethPriceWei,omitempty"`
	EventLogId                     int64          `json:"eventLogId"`
	Message                        *string        `json:"message,omitempty"`
	NftDonation                    *NftDonation   `json:"nftDonation,omitempty"`
	OccurredAt                     time.Time      `json:"occurredAt"`
	Position                       int64          `json:"position"`
	PrizeAt                        time.Time      `json:"prizeAt"`
	RandomWalkTokenId              *int64         `json:"randomWalkTokenId,omitempty"`
	Round                          int64          `json:"round"`
	TransactionHash                string         `json:"transactionHash"`
}

// BidType defines model for BidType.
type BidType string

// CharityAllocation defines model for CharityAllocation.
type CharityAllocation struct {
	AmountWei        string   `json:"amountWei"`
	CharityAddresses []string `json:"charityAddresses"`
}

// ChronoWarriorPrize defines model for ChronoWarriorPrize.
type ChronoWarriorPrize struct {
	CstAmountWei  string `json:"cstAmountWei"`
	EthAmountWei  string `json:"ethAmountWei"`
	NftTokenId    int64  `json:"nftTokenId"`
	WinnerAddress string `json:"winnerAddress"`
}

// ClaimTransaction defines model for ClaimTransaction.
type ClaimTransaction struct {
	BlockNumber     int64     `json:"blockNumber"`
	EventLogId      int64     `json:"eventLogId"`
	OccurredAt      time.Time `json:"occurredAt"`
	TransactionHash string    `json:"transactionHash"`
}

// CosmicGameCurrentRound defines model for CosmicGameCurrentRound.
type CosmicGameCurrentRound struct {
	LastBidderAddress                  *string         `json:"lastBidderAddress,omitempty"`
	MainPrizeAmountWei                 string          `json:"mainPrizeAmountWei"`
	MainPrizeTimeIncrementMicroseconds string          `json:"mainPrizeTimeIncrementMicroseconds"`
	NextEthBidPriceWei                 string          `json:"nextEthBidPriceWei"`
	RafflePrizeAmountWei               string          `json:"rafflePrizeAmountWei"`
	Round                              int64           `json:"round"`
	SecondsUntilMainPrize              int64           `json:"secondsUntilMainPrize"`
	StakingRewardAmountWei             string          `json:"stakingRewardAmountWei"`
	Statistics                         RoundStatistics `json:"statistics"`
	Status                             RoundStatus     `json:"status"`
}

// CosmicGameRound defines model for CosmicGameRound.
type CosmicGameRound struct {
	Charity           *CharityAllocation  `json:"charity,omitempty"`
	ChronoWarrior     *ChronoWarriorPrize `json:"chronoWarrior,omitempty"`
	Claim             ClaimTransaction    `json:"claim"`
	EnduranceChampion *TokenPrize         `json:"enduranceChampion,omitempty"`
	LastCstBidder     *TokenPrize         `json:"lastCstBidder,omitempty"`
	MainPrize         MainPrize           `json:"mainPrize"`
	Round             int64               `json:"round"`
	Staking           *StakingAllocation  `json:"staking,omitempty"`
	Statistics        RoundStatistics     `json:"statistics"`
	Status            RoundStatus         `json:"status"`
}

// CosmicGameRoundSummary defines model for CosmicGameRoundSummary.
type CosmicGameRoundSummary struct {
	CompletedAt          time.Time   `json:"completedAt"`
	DonatedNftCount      int64       `json:"donatedNftCount"`
	Erc20DonationCount   int64       `json:"erc20DonationCount"`
	MainPrize            MainPrize   `json:"mainPrize"`
	RaffleEthDepositsWei string      `json:"raffleEthDepositsWei"`
	RaffleNftCount       int64       `json:"raffleNftCount"`
	Round                int64       `json:"round"`
	Status               RoundStatus `json:"status"`
	TotalBids            int64       `json:"totalBids"`
}

// Erc20Donation defines model for Erc20Donation.
type Erc20Donation struct {
	AmountWei    string `json:"amountWei"`
	TokenAddress string `json:"tokenAddress"`
}

// MainPrize defines model for MainPrize.
type MainPrize struct {
	CstAmountWei                *string    `json:"cstAmountWei,omitempty"`
	EthAmountWei                string     `json:"ethAmountWei"`
	NftTokenId                  int64      `json:"nftTokenId"`
	SecondaryPrizeClaimDeadline *time.Time `json:"secondaryPrizeClaimDeadline,omitempty"`
	Seed                        *string    `json:"seed,omitempty"`
	WinnerAddress               string     `json:"winnerAddress"`
}

// NftDonation defines model for NftDonation.
type NftDonation struct {
	TokenAddress string `json:"tokenAddress"`
	TokenId      int64  `json:"tokenId"`
	TokenUri     string `json:"tokenUri"`
}

// PageMeta defines model for PageMeta.
type PageMeta struct {
	Limit      int     `json:"limit"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// RaffleNftPool defines model for RaffleNftPool.
type RaffleNftPool string

// RoundBidPage defines model for RoundBidPage.
type RoundBidPage struct {
	Data []Bid    `json:"data"`
	Meta PageMeta `json:"meta"`
}

// RoundPage defines model for RoundPage.
type RoundPage struct {
	Data []CosmicGameRoundSummary `json:"data"`
	Meta PageMeta                 `json:"meta"`
}

// RoundPrize defines model for RoundPrize.
type RoundPrize struct {
	BlockNumber int64 `json:"blockNumber"`

	// CstAmountWei Present only for CST-denominated prize types.
	CstAmountWei *string `json:"cstAmountWei,omitempty"`

	// EthAmountWei Present only for ETH-denominated prize types.
	EthAmountWei *string `json:"ethAmountWei,omitempty"`
	EventLogId   int64   `json:"eventLogId"`

	// NftTokenId Present only for Cosmic Signature NFT prize types.
	NftTokenId      *int64         `json:"nftTokenId,omitempty"`
	OccurredAt      time.Time      `json:"occurredAt"`
	Round           int64          `json:"round"`
	TransactionHash string         `json:"transactionHash"`
	Type            RoundPrizeType `json:"type"`

	// WinnerAddress Omitted for the round-wide Cosmic Signature staking allocation.
	WinnerAddress *string `json:"winnerAddress,omitempty"`
	WinnerIndex   int64   `json:"winnerIndex"`
}

// RoundPrizePage defines model for RoundPrizePage.
type RoundPrizePage struct {
	Data []RoundPrize `json:"data"`
	Meta PageMeta     `json:"meta"`
}

// RoundPrizeType defines model for RoundPrizeType.
type RoundPrizeType string

// RoundRaffleEthDeposit defines model for RoundRaffleEthDeposit.
type RoundRaffleEthDeposit struct {
	BlockNumber     int64     `json:"blockNumber"`
	Claimed         bool      `json:"claimed"`
	EthAmountWei    string    `json:"ethAmountWei"`
	EventLogId      int64     `json:"eventLogId"`
	OccurredAt      time.Time `json:"occurredAt"`
	Round           int64     `json:"round"`
	TransactionHash string    `json:"transactionHash"`
	WinnerAddress   string    `json:"winnerAddress"`
	WinnerIndex     int64     `json:"winnerIndex"`
}

// RoundRaffleEthDepositPage defines model for RoundRaffleEthDepositPage.
type RoundRaffleEthDepositPage struct {
	Data []RoundRaffleEthDeposit `json:"data"`
	Meta PageMeta                `json:"meta"`
}

// RoundRaffleNftWinner defines model for RoundRaffleNftWinner.
type RoundRaffleNftWinner struct {
	BlockNumber     int64     `json:"blockNumber"`
	CstAmountWei    string    `json:"cstAmountWei"`
	EventLogId      int64     `json:"eventLogId"`
	IsRandomWalk    bool      `json:"isRandomWalk"`
	NftTokenId      int64     `json:"nftTokenId"`
	OccurredAt      time.Time `json:"occurredAt"`
	Round           int64     `json:"round"`
	TransactionHash string    `json:"transactionHash"`
	WinnerAddress   string    `json:"winnerAddress"`
	WinnerIndex     int64     `json:"winnerIndex"`
}

// RoundRaffleNftWinnerPage defines model for RoundRaffleNftWinnerPage.
type RoundRaffleNftWinnerPage struct {
	Data []RoundRaffleNftWinner `json:"data"`
	Meta PageMeta               `json:"meta"`
}

// RoundStatistics defines model for RoundStatistics.
type RoundStatistics struct {
	ActivatedAt                    *time.Time `json:"activatedAt,omitempty"`
	DonatedNftCount                int64      `json:"donatedNftCount"`
	DonationAmountWei              string     `json:"donationAmountWei"`
	DonationCount                  int64      `json:"donationCount"`
	Erc20DonationCount             int64      `json:"erc20DonationCount"`
	ParameterWindowDurationSeconds *int64     `json:"parameterWindowDurationSeconds,omitempty"`
	ParameterWindowStartedAt       *time.Time `json:"parameterWindowStartedAt,omitempty"`
	RaffleEthDepositsWei           string     `json:"raffleEthDepositsWei"`
	RaffleNftCount                 int64      `json:"raffleNftCount"`
	RoundDurationSeconds           *int64     `json:"roundDurationSeconds,omitempty"`
	RoundEndedAt                   *time.Time `json:"roundEndedAt,omitempty"`
	RoundStartedAt                 *time.Time `json:"roundStartedAt,omitempty"`
	TotalBids                      int64      `json:"totalBids"`
}

// RoundStatus defines model for RoundStatus.
type RoundStatus string

// StakingAllocation defines model for StakingAllocation.
type StakingAllocation struct {
	AmountPerTokenWei string `json:"amountPerTokenWei"`
	AmountWei         string `json:"amountWei"`
	DepositId         int64  `json:"depositId"`
	StakedTokenCount  int64  `json:"stakedTokenCount"`
}

// TokenPrize defines model for TokenPrize.
type TokenPrize struct {
	CstAmountWei  string `json:"cstAmountWei"`
	NftTokenId    int64  `json:"nftTokenId"`
	WinnerAddress string `json:"winnerAddress"`
}

// BidPosition defines model for BidPosition.
type BidPosition = int64

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// RaffleNftPoolParam defines model for RaffleNftPoolParam.
type RaffleNftPoolParam = RaffleNftPool

// Round defines model for Round.
type Round = int64

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// InternalError defines model for InternalError.
type InternalError = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Problem

// ListRoundsParams defines parameters for ListRounds.
type ListRoundsParams struct {
	// Cursor Opaque continuation cursor returned by the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of resources to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRoundBidsParams defines parameters for ListRoundBids.
type ListRoundBidsParams struct {
	// Cursor Opaque continuation cursor returned by the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of resources to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRoundPrizesParams defines parameters for ListRoundPrizes.
type ListRoundPrizesParams struct {
	// Cursor Opaque continuation cursor returned by the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of resources to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRoundRaffleEthDepositsParams defines parameters for ListRoundRaffleEthDeposits.
type ListRoundRaffleEthDepositsParams struct {
	// Cursor Opaque continuation cursor returned by the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of resources to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRoundRaffleNftWinnersParams defines parameters for ListRoundRaffleNftWinners.
type ListRoundRaffleNftWinnersParams struct {
	// Pool Select bidder winners or RandomWalk-staker winners.
	Pool RaffleNftPoolParam `form:"pool" json:"pool"`

	// Cursor Opaque continuation cursor returned by the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of resources to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List completed CosmicGame rounds
	// (GET /api/v2/cosmicgame/rounds)
	ListRounds(w http.ResponseWriter, r *http.Request, params ListRoundsParams)
	// Get the current open CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/current)
	GetCurrentRound(w http.ResponseWriter, r *http.Request)
	// Get one completed CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round})
	GetRound(w http.ResponseWriter, r *http.Request, round Round)
	// List bids in one CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round}/bids)
	ListRoundBids(w http.ResponseWriter, r *http.Request, round Round, params ListRoundBidsParams)
	// Get one bid by its position in a CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round}/bids/{position})
	GetRoundBid(w http.ResponseWriter, r *http.Request, round Round, position BidPosition)
	// List prizes awarded in one completed CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round}/prizes)
	ListRoundPrizes(w http.ResponseWriter, r *http.Request, round Round, params ListRoundPrizesParams)
	// List bidder raffle ETH wallet deposits in one completed round
	// (GET /api/v2/cosmicgame/rounds/{round}/raffle-eth-deposits)
	ListRoundRaffleEthDeposits(w http.ResponseWriter, r *http.Request, round Round, params ListRoundRaffleEthDepositsParams)
	// List raffle NFT winners in one completed round
	// (GET /api/v2/cosmicgame/rounds/{round}/raffle-nft-winners)
	ListRoundRaffleNftWinners(w http.ResponseWriter, r *http.Request, round Round, params ListRoundRaffleNftWinnersParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListRounds operation middleware
func (siw *ServerInterfaceWrapper) ListRounds(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRoundsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRounds(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentRound operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentRound(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentRound(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRound operation middleware
func (siw *ServerInterfaceWrapper) GetRound(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "round" -------------
	var round Round

	err = runtime.BindStyledParameterWithOptions("simple", "round", r.PathValue("round"), &round, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "round", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRound(w, r, round)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoundBids operation middleware
func (siw *ServerInterfaceWrapper) ListRoundBids(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "round" -------------
	var round Round

	err = runtime.BindStyledParameterWithOptions("simple", "round", r.PathValue("round"), &round, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "round", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRoundBidsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoundBids(w, r, round, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoundBid operation middleware
func (siw *ServerInterfaceWrapper) GetRoundBid(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "round" -------------
	var round Round

	err = runtime.BindStyledParameterWithOptions("simple", "round", r.PathValue("round"), &round, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "round", Err: err})
		return
	}

	// ------------- Path parameter "position" -------------
	var position BidPosition

	err = runtime.BindStyledParameterWithOptions("simple", "position", r.PathValue("position"), &position, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "position", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoundBid(w, r, round, position)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoundPrizes operation middleware
func (siw *ServerInterfaceWrapper) ListRoundPrizes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "round" -------------
	var round Round

	err = runtime.BindStyledParameterWithOptions("simple", "round", r.PathValue("round"), &round, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "round", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRoundPrizesParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoundPrizes(w, r, round, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoundRaffleEthDeposits operation middleware
func (siw *ServerInterfaceWrapper) ListRoundRaffleEthDeposits(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "round" -------------
	var round Round

	err = runtime.BindStyledParameterWithOptions("simple", "round", r.PathValue("round"), &round, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "round", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRoundRaffleEthDepositsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoundRaffleEthDeposits(w, r, round, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoundRaffleNftWinners operation middleware
func (siw *ServerInterfaceWrapper) ListRoundRaffleNftWinners(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "round" -------------
	var round Round

	err = runtime.BindStyledParameterWithOptions("simple", "round", r.PathValue("round"), &round, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "round", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRoundRaffleNftWinnersParams

	// ------------- Required query parameter "pool" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "pool", r.URL.Query(), &params.Pool, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pool"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pool", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoundRaffleNftWinners(w, r, round, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds", wrapper.ListRounds)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/current", wrapper.GetCurrentRound)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/{round}", wrapper.GetRound)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/{round}/bids", wrapper.ListRoundBids)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/{round}/bids/{position}", wrapper.GetRoundBid)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/{round}/prizes", wrapper.ListRoundPrizes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/{round}/raffle-eth-deposits", wrapper.ListRoundRaffleEthDeposits)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v2/cosmicgame/rounds/{round}/raffle-nft-winners", wrapper.ListRoundRaffleNftWinners)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type BidJSONResponse Bid

type CosmicGameCurrentRoundJSONResponse CosmicGameCurrentRound

type CosmicGameRoundJSONResponse CosmicGameRound

type InternalErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type RoundBidPageJSONResponse RoundBidPage

type RoundPageJSONResponse RoundPage

type RoundPrizePageJSONResponse RoundPrizePage

type RoundRaffleEthDepositPageJSONResponse RoundRaffleEthDepositPage

type RoundRaffleNftWinnerPageJSONResponse RoundRaffleNftWinnerPage

type ServiceUnavailableResponseHeaders struct {
	RetryAfter int
}
type ServiceUnavailableApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ServiceUnavailableResponseHeaders
}

type ListRoundsRequestObject struct {
	Params ListRoundsParams
}

type ListRoundsResponseObject interface {
	VisitListRoundsResponse(w http.ResponseWriter) error
}

type ListRounds200JSONResponse struct{ RoundPageJSONResponse }

func (response ListRounds200JSONResponse) VisitListRoundsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRounds400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListRounds400ApplicationProblemPlusJSONResponse) VisitListRoundsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListRounds500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListRounds500ApplicationProblemPlusJSONResponse) VisitListRoundsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentRoundRequestObject struct {
}

type GetCurrentRoundResponseObject interface {
	VisitGetCurrentRoundResponse(w http.ResponseWriter) error
}

type GetCurrentRound200JSONResponse struct {
	CosmicGameCurrentRoundJSONResponse
}

func (response GetCurrentRound200JSONResponse) VisitGetCurrentRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentRound500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetCurrentRound500ApplicationProblemPlusJSONResponse) VisitGetCurrentRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentRound503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response GetCurrentRound503ApplicationProblemPlusJSONResponse) VisitGetCurrentRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoundRequestObject struct {
	Round Round `json:"round"`
}

type GetRoundResponseObject interface {
	VisitGetRoundResponse(w http.ResponseWriter) error
}

type GetRound200JSONResponse struct{ CosmicGameRoundJSONResponse }

func (response GetRound200JSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRound400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetRound400ApplicationProblemPlusJSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRound404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetRound404ApplicationProblemPlusJSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRound500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetRound500ApplicationProblemPlusJSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundBidsRequestObject struct {
	Round  Round `json:"round"`
	Params ListRoundBidsParams
}

type ListRoundBidsResponseObject interface {
	VisitListRoundBidsResponse(w http.ResponseWriter) error
}

type ListRoundBids200JSONResponse struct{ RoundBidPageJSONResponse }

func (response ListRoundBids200JSONResponse) VisitListRoundBidsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundBids400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListRoundBids400ApplicationProblemPlusJSONResponse) VisitListRoundBidsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundBids500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListRoundBids500ApplicationProblemPlusJSONResponse) VisitListRoundBidsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoundBidRequestObject struct {
	Round    Round       `json:"round"`
	Position BidPosition `json:"position"`
}

type GetRoundBidResponseObject interface {
	VisitGetRoundBidResponse(w http.ResponseWriter) error
}

type GetRoundBid200JSONResponse struct{ BidJSONResponse }

func (response GetRoundBid200JSONResponse) VisitGetRoundBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoundBid400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetRoundBid400ApplicationProblemPlusJSONResponse) VisitGetRoundBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoundBid404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetRoundBid404ApplicationProblemPlusJSONResponse) VisitGetRoundBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRoundBid500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetRoundBid500ApplicationProblemPlusJSONResponse) VisitGetRoundBidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundPrizesRequestObject struct {
	Round  Round `json:"round"`
	Params ListRoundPrizesParams
}

type ListRoundPrizesResponseObject interface {
	VisitListRoundPrizesResponse(w http.ResponseWriter) error
}

type ListRoundPrizes200JSONResponse struct{ RoundPrizePageJSONResponse }

func (response ListRoundPrizes200JSONResponse) VisitListRoundPrizesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundPrizes400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListRoundPrizes400ApplicationProblemPlusJSONResponse) VisitListRoundPrizesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundPrizes404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListRoundPrizes404ApplicationProblemPlusJSONResponse) VisitListRoundPrizesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundPrizes500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListRoundPrizes500ApplicationProblemPlusJSONResponse) VisitListRoundPrizesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundRaffleEthDepositsRequestObject struct {
	Round  Round `json:"round"`
	Params ListRoundRaffleEthDepositsParams
}

type ListRoundRaffleEthDepositsResponseObject interface {
	VisitListRoundRaffleEthDepositsResponse(w http.ResponseWriter) error
}

type ListRoundRaffleEthDeposits200JSONResponse struct {
	RoundRaffleEthDepositPageJSONResponse
}

func (response ListRoundRaffleEthDeposits200JSONResponse) VisitListRoundRaffleEthDepositsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundRaffleEthDeposits400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListRoundRaffleEthDeposits400ApplicationProblemPlusJSONResponse) VisitListRoundRaffleEthDepositsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundRaffleEthDeposits404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListRoundRaffleEthDeposits404ApplicationProblemPlusJSONResponse) VisitListRoundRaffleEthDepositsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundRaffleEthDeposits500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListRoundRaffleEthDeposits500ApplicationProblemPlusJSONResponse) VisitListRoundRaffleEthDepositsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundRaffleNftWinnersRequestObject struct {
	Round  Round `json:"round"`
	Params ListRoundRaffleNftWinnersParams
}

type ListRoundRaffleNftWinnersResponseObject interface {
	VisitListRoundRaffleNftWinnersResponse(w http.ResponseWriter) error
}

type ListRoundRaffleNftWinners200JSONResponse struct {
	RoundRaffleNftWinnerPageJSONResponse
}

func (response ListRoundRaffleNftWinners200JSONResponse) VisitListRoundRaffleNftWinnersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundRaffleNftWinners400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListRoundRaffleNftWinners400ApplicationProblemPlusJSONResponse) VisitListRoundRaffleNftWinnersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundRaffleNftWinners404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListRoundRaffleNftWinners404ApplicationProblemPlusJSONResponse) VisitListRoundRaffleNftWinnersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoundRaffleNftWinners500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListRoundRaffleNftWinners500ApplicationProblemPlusJSONResponse) VisitListRoundRaffleNftWinnersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List completed CosmicGame rounds
	// (GET /api/v2/cosmicgame/rounds)
	ListRounds(ctx context.Context, request ListRoundsRequestObject) (ListRoundsResponseObject, error)
	// Get the current open CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/current)
	GetCurrentRound(ctx context.Context, request GetCurrentRoundRequestObject) (GetCurrentRoundResponseObject, error)
	// Get one completed CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round})
	GetRound(ctx context.Context, request GetRoundRequestObject) (GetRoundResponseObject, error)
	// List bids in one CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round}/bids)
	ListRoundBids(ctx context.Context, request ListRoundBidsRequestObject) (ListRoundBidsResponseObject, error)
	// Get one bid by its position in a CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round}/bids/{position})
	GetRoundBid(ctx context.Context, request GetRoundBidRequestObject) (GetRoundBidResponseObject, error)
	// List prizes awarded in one completed CosmicGame round
	// (GET /api/v2/cosmicgame/rounds/{round}/prizes)
	ListRoundPrizes(ctx context.Context, request ListRoundPrizesRequestObject) (ListRoundPrizesResponseObject, error)
	// List bidder raffle ETH wallet deposits in one completed round
	// (GET /api/v2/cosmicgame/rounds/{round}/raffle-eth-deposits)
	ListRoundRaffleEthDeposits(ctx context.Context, request ListRoundRaffleEthDepositsRequestObject) (ListRoundRaffleEthDepositsResponseObject, error)
	// List raffle NFT winners in one completed round
	// (GET /api/v2/cosmicgame/rounds/{round}/raffle-nft-winners)
	ListRoundRaffleNftWinners(ctx context.Context, request ListRoundRaffleNftWinnersRequestObject) (ListRoundRaffleNftWinnersResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListRounds operation middleware
func (sh *strictHandler) ListRounds(w http.ResponseWriter, r *http.Request, params ListRoundsParams) {
	var request ListRoundsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRounds(ctx, request.(ListRoundsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRounds")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRoundsResponseObject); ok {
		if err := validResponse.VisitListRoundsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentRound operation middleware
func (sh *strictHandler) GetCurrentRound(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentRoundRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentRound(ctx, request.(GetCurrentRoundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentRound")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentRoundResponseObject); ok {
		if err := validResponse.VisitGetCurrentRoundResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRound operation middleware
func (sh *strictHandler) GetRound(w http.ResponseWriter, r *http.Request, round Round) {
	var request GetRoundRequestObject

	request.Round = round

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRound(ctx, request.(GetRoundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRound")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRoundResponseObject); ok {
		if err := validResponse.VisitGetRoundResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRoundBids operation middleware
func (sh *strictHandler) ListRoundBids(w http.ResponseWriter, r *http.Request, round Round, params ListRoundBidsParams) {
	var request ListRoundBidsRequestObject

	request.Round = round
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRoundBids(ctx, request.(ListRoundBidsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRoundBids")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRoundBidsResponseObject); ok {
		if err := validResponse.VisitListRoundBidsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRoundBid operation middleware
func (sh *strictHandler) GetRoundBid(w http.ResponseWriter, r *http.Request, round Round, position BidPosition) {
	var request GetRoundBidRequestObject

	request.Round = round
	request.Position = position

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRoundBid(ctx, request.(GetRoundBidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRoundBid")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRoundBidResponseObject); ok {
		if err := validResponse.VisitGetRoundBidResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRoundPrizes operation middleware
func (sh *strictHandler) ListRoundPrizes(w http.ResponseWriter, r *http.Request, round Round, params ListRoundPrizesParams) {
	var request ListRoundPrizesRequestObject

	request.Round = round
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRoundPrizes(ctx, request.(ListRoundPrizesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRoundPrizes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRoundPrizesResponseObject); ok {
		if err := validResponse.VisitListRoundPrizesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRoundRaffleEthDeposits operation middleware
func (sh *strictHandler) ListRoundRaffleEthDeposits(w http.ResponseWriter, r *http.Request, round Round, params ListRoundRaffleEthDepositsParams) {
	var request ListRoundRaffleEthDepositsRequestObject

	request.Round = round
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRoundRaffleEthDeposits(ctx, request.(ListRoundRaffleEthDepositsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRoundRaffleEthDeposits")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRoundRaffleEthDepositsResponseObject); ok {
		if err := validResponse.VisitListRoundRaffleEthDepositsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRoundRaffleNftWinners operation middleware
func (sh *strictHandler) ListRoundRaffleNftWinners(w http.ResponseWriter, r *http.Request, round Round, params ListRoundRaffleNftWinnersParams) {
	var request ListRoundRaffleNftWinnersRequestObject

	request.Round = round
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRoundRaffleNftWinners(ctx, request.(ListRoundRaffleNftWinnersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRoundRaffleNftWinners")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRoundRaffleNftWinnersResponseObject); ok {
		if err := validResponse.VisitListRoundRaffleNftWinnersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fzdb9s4Ev9XCN6+rRx7s+kC9Vvqpm2ANhsk6QW4bg6gxbHNjUSqJOUkG/h/P5DUt2RbkuMkLe6pjc2P",
	"4cxvhvPB8SP2RRgJDlwrPH7EEZEkBA3S/vWO0XOhmGaCmz8pKF+yyP2J/+QwmBIFFE0ZRVEyDt0xvWAc",
	"6QUgKWJOD7CHmRkfEb3AHuYkBPNXuq6HJXyPmQSKx1rG4GHlLyAkZsOZkCHReIwZ138cYQ+HjLMwDvH4",
	"Nw/rhwjcVzAHiVcrD09iqYRsIDUi32NAvuCa8ZhYOn07FknQseTmEA+W5kjCkolYoYjMIaP9ewzyISfe",
	"zcVFUkNy/xn4XC/w+M1vh5bS9O+cVqUl43NL6mcWMl2n9Au5NwdEPA6nIJGYIQlKxNIHhbRIqF1HVmDX",
	"LFJFYUbiQOPxm5FnSHTMOxyNtrLygsxmAZzN9LkQwblBRZ3YSwjA10b8FCS6Y5yDVEhIdEE4FeE1CW4H",
	"SpPb/Mt1lEdCBBuR8IuEGR7jfw1zuA7dt2pYItURb4BXp/c/IEUC2YlQIfM/kjBBacLwNWC1Q3oiddTA",
	"3pVZSkWCK3B6RugFfI9BWUQYmAK3/yVRFDDfAnYYSTENIPz1b+W0sR1zzt0st2mZHcfInNLIy0oDZbqP",
	"mEKML0nA6AFeecYMbKCrGz1mrQZaroy5cCxwBsVunEtpEksJXGeCfRJa1iy/hjzfjUEiAp6AZiZFaK2G",
	"T/wFUBSwpbMykvgaKU00VM6xrwNspDxnrFkjAPO/xDavPHzKNUhOghMpne18LvwVSEO+iAOKuNBoCjmV",
	"lr4zoT9s4do+STO8SkwwogKUJRLumdKWOst4c0+SOTyZXEuLNpD3JweDrmkA9pqy14QF5JRRlZP19DR1",
	"IKgCtSJZkv0De6AtW7YdgZEZrxC5I5ICRYwj0qgfdnF3x5zoxXuwnsvTk9+4Q7uTJBewtCugk6tP6I4E",
	"AWhE3VKqeo6zmb62F/K+jlHeoCWCHflnH64yV4JxJDgg4x3YI1yCXDIfvnKyJCwws5/bKKw39ObSNKYh",
	"uSaCB5QRabyKBRCaeNUXoOXD4HimQTb5VL7gVKGYaxbYu4XDvUaGPBoHydYDt6OEmQS1ONjomWz08+wp",
	"k6MnDr9lI6XWOSfBuRQRSM2MnzIjgQIPR4WPHvGU0YnSF2C06DgUMdfXwFwkoc29gsf4v99Gg7c3v/6C",
	"a36wZ6Zf2c+2eg12mJtBQR5TKkGpykaje7MVGcyOBx9uHo9Gq+Y9A+Hfnll/r7Pr5mFf6fex9hfHsW9Y",
	"9D6WFm6J3PoteC6ZD5345qc87zQLpH84ei84SSO6TTw/KQ02s/WiO6GwBK4/i/kp7RzQeTgEpRILVVuY",
	"z3Tbk5wVhq48LHyro/RYl0iiRMNAsxCajhEVwuCOh7D3TJe9ZBY9XYlb4Ns41wgqmXpMHedpSbgiFtmf",
	"iFps1K8/jpr0a1U0Rt+K8i9rXn2vkmSqiu5lQVghc5Baj5zJFc24ycgT07/B10k0k5oc4IYR3wyycZHv",
	"bhns4ZjfcnHHC+vkYposiGT64TgIhJ/BsIPlJN2tpZ9s6XjilmEawn52MPmASEkeanKrbeUVCG5i62Qh",
	"BRfXREompPXFOvLDV7rHBQJ60WMWn+n+uuW8k/43UIXT5eUqJ/LKbClR3iiFgLDwKlesrrf5TlfjTra+",
	"j1V+NdaqURRrkxcdBBIQpd/t7PGEhHGrkj1UJZt7xUI45b6EELj+wnwpVO7ztFQ7uNcnemEi286OhAsP",
	"+p6i732YHPGr8ca/pJzos44mt4zPe/vJxuFnSjNftYrCLvPhyeS4/cRY1fQivXuTlRoluY5ZjfBbI8+1",
	"jGqFwxKbNqtkH11MrsStSbmaX2Bv7sLtuH2F2lVqljCmfevUqv03ZpnTWBLuw2RBwqiFv2wvmGxfY4Im",
	"qRXqNjUsasymaTladtFVB51te126YWX5vDb9csIucrAruC/jMCTyoSvG0wRYl2uYmuAK6NlMT4y+9vEc",
	"irFm30V6oq2Sd1M9bqUdTr4D2LtizsNaaBK8Yz3SFFvxWsBNGbX5nnWgNAp+jUhqvG7SgZNqgmO/8Zg2",
	"1u7JAoHSatvCrZIz8jNGWe5SJ/LBntLea++B0IBxaG+ZFABtzB49bwy3JWg7K6eyOkhzRwAmCO4lHzvz",
	"q2QN7G3CtY2oKgjPlmhiyjmZwxfQpGvAlL6raP/awXmz+duRrk85imd12zeeJyksdDsOBU1Y0AhhxpU2",
	"Xl1JdrFkAwkzkGC+WRNIuHsjY9Cbt28LDDoaNYub6aA5EauTZFr21gSTqYj1eBoQfou91rRVUeMSe27f",
	"jO4mzpbffxTSei6DWMrsXdrnKI35vGolt4uUiMNplovb+gKimn3zcJhgfWNxKtWJKrMsAckajSwqloP3",
	"dbA1DujLnLXH1bhzXah0RZbLeucSlH08woMHNBMSTS6vBhS4CJl1iVw1Gpll7SOpftfylj1Prj49wZ67",
	"JPnKHsE2Flk8oUs250TH0pWGKzR3FFKfJOPLlVJy29ru8UNaIq05N5Xae8i0Eb/hcfZMc3DHKNRZnsTU",
	"iGTRcgUp7dwMR9Epp3C/a+jRv6CUBi1FYpLtNtuRfRvOgsV6OWNZrYllMdyJLY5lf05UKcI7m5k/Szmi",
	"ho/cpFoiyo2sfexGl1JmjojSRw2j3Hru2s/e01Q+cdOKn7hZVR+hOLr5OzfPtyqTaUySXTL7rnUyqk99",
	"nveeMpFUKSqaChEA4f3jvGev+7ykSd41cnzVxnBbLTLBzlpLsu6Z3F4tZ02dXsSIVh6+vajv+Qxqy1T+",
	"yL/ZluyU/fm/VXjFVqEg2dr7hBIu2irLM5qJXEFfxEpclupMXbLTvmZL8uyFGZrkJXuYF7pjOedJakJZ",
	"T8s141Tc7f5as7LgpSayo1BeQ8Fpdz7YZU447WGie/DsyQpXe6tGVfHepDobrYJLyqbRV1ZPMxY6guYX",
	"iPVKdp+K1zlIa807wbBHsSxpRjjtW9oHasnsh/uqrc5oKR7Fa+BIw95NYiy8e3iOetxrfr+43juoM25l",
	"6xgzUU9SXSQ9VwMhGXANFB2fn9qUVe5fIMKLnZwH6N+HrnVRS0FjH+hfnKUPhUgQPKC7BQvA5rxmUvwD",
	"HC1/y7s4JISEcVVo2/iLZwWIMb64nnxE74h/C9zRsjzEHl6CVI7g0cGbg5F1XSPgJGJ4jH8/GB387tJl",
	"C8voIYnYcHk4dDmDOQlh6JqjzJdzsLA24LDKbGSLPzPl3g0q7JWas781eyn5kGFS0Fp5W0e6XuTVTaUr",
	"9XA0WucMZeOKbWEePmozo9DsuvLwmzZTyi2Ktmclfd1iOVTo26o29to6I5kbjuH6dzdmrbVSGSa9PGul",
	"8xF06W1nHwaua0Ltxxoz6/ftsxoaqcpc/QjaNbYWm16r/NuFtY/239Um1qY87Qb7hH03u8kiE0IPSB+N",
	"jrZPybpan0IHjLQEhw1q8ASiGk5ZG0OVOFe9hOa9JqOW9d++oF0zLE+7INuJ1Aqpg0CHj2k/zXZdfMfo",
	"/iRb/K2RflJLCus/lMZOmf3lEaZV/gsqthP56aXt+p23K/C5G/czqHChJfwHwYXV+npneh/jnsi7JTpc",
	"ODsAvRikXePboVLNvP8cqGnuxP+RALT1BwHqmNrkJdhluiKJz/Qg6eNvC6QsN7tHHDX8rtFrRF/lBxR+",
	"JPCt/x2HrmizD3jlMoVALAM8xkO8uln9LwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
