#!/bin/bash

rm ./etl/cmd/augur/augur
rm ./etl/cmd/tokens/tokens
rm ./etl/cmd/layer1/layer1
rm ./etl/cmd/balancer/balancer
rm ./etl/cmd/uniswap/uniswap
rm ./etl/cmd/ensscan/ensscan
rm ./etl/cmd/ensscan/tools/scanpropnames
rm ./etl/cmd/ensscan/tools/labelhash
rm ./etl/cmd/ensscan/tools/namehash
rm ./etl/cmd/ensscan/tools/lookup
rm ./etl/cmd/ensscan/tools/pk
rm ./etl/cmd/ensscan/tools/check_ens
rm ./etl/cmd/arbitrum/arbitrum
rm ./etl/cmd/arbitrum-augur/arbitrum-augur
rm ./etl/cmd/erc20/erc20
rm ./etl/cmd/erc1155/erc1155
rm ./etl/cmd/polysync/polysync
rm ./etl/cmd/polymarkets/polymarkets
rm ./etl/dmesh/dmesh
rm ./etl/tools/augur_blocks
rm ./etl/tools/dai_balances
rm ./etl/tools/toprated
rm ./etl/tools/uniqueaddrs
rm ./etl/tools/gas_usage
rm ./etl/tools/stbalance
rm ./etl/tools/check_owner
rm ./etl/tools/check_wallet
rm ./etl/tools/load_abi
rm ./etl/tools/load_abi_artifacts
rm ./etl/tests/verif_dai_balances
rm ./etl/tests/verif_cash_flow
rm ./etl/ens/scanpropnames
rm ./etl/ens/scantlds
rm ./server/server
rm ./etl/cmd/arbitrum-augur/scripts/cash_faucet
rm ./etl/cmd/arbitrum-augur/scripts/new_sports
rm ./etl/cmd/arbitrum-augur/scripts/new_trusted
rm ./etl/cmd/arbitrum-augur/multicall/deploy
rm ./etl/cmd/arbitrum-augur/tools/balswap
rm ./etl/cmd/arbitrum-augur/tools/erc20bal
rm ./etl/cmd/arbitrum-augur/tools/getmarket
rm ./etl/cmd/arbitrum-augur/tools/approve
rm ./etl/cmd/arbitrum-augur/tools/burnshares
rm ./etl/cmd/arbitrum-augur/tools/dump-vm-trace
rm ./etl/cmd/arbitrum-augur/tools/getcode
rm ./etl/cmd/arbitrum-augur/tools/spotprice
rm ./etl/cmd/arbitrum-augur/tools/trade2price
rm ./etl/cmd/arbitrum-augur/tools/usershares
rm ./etl/cmd/arbitrum-augur/tools/allowance
rm ./etl/cmd/randomwalk/randomwalk
rm ./etl/cmd/randomwalk/scripts/accept_offer
rm ./etl/cmd/randomwalk/scripts/approve
rm ./etl/cmd/randomwalk/scripts/cancel_offer
rm ./etl/cmd/randomwalk/scripts/mint
rm ./etl/cmd/randomwalk/scripts/new_offer
rm ./etl/cmd/randomwalk/scripts/setname
rm ./etl/cmd/randomwalk/scripts/transfer
