#!/bin/bash

rm ./etl/cmd/augur/augur
rm ./etl/cmd/tokens/tokens
rm ./etl/cmd/layer1/layer1
rm ./etl/cmd/balancer/balancer
rm ./etl/cmd/uniswap/uniswap
rm ./etl/cmd/ensscan/ensscan
rm ./etl/cmd/ensscan/tools/scanpropnames
rm ./etl/cmd/ensscan/tools/labelhash
rm ./etl/cmd/ensscan/tools/namehash
rm ./etl/cmd/ensscan/tools/lookup
rm ./etl/cmd/ensscan/tools/pk
rm ./etl/cmd/ensscan/tools/check_ens
rm ./etl/cmd/arbitrum/arbitrum
rm ./etl/cmd/arbitrum-augur/arbitrum-augur
rm ./etl/dmesh/dmesh
rm ./etl/tools/augur_blocks
rm ./etl/tools/dai_balances
rm ./etl/tools/toprated
rm ./etl/tools/uniqueaddrs
rm ./etl/tools/gas_usage
rm ./etl/tools/stbalance
rm ./etl/tools/check_owner
rm ./etl/tools/check_wallet
rm ./etl/tests/verif_dai_balances
rm ./etl/tests/verif_cash_flow
rm ./etl/ens/scanpropnames
rm ./etl/ens/scantlds
rm ./server/server
rm ./etl/cmd/arbitrum-augur/scripts/cash_faucet
rm ./etl/cmd/arbitrum-augur/scripts/new_sports
rm ./etl/cmd/arbitrum-augur/scripts/new_trusted
