// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: layer1.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAddressID = `-- name: GetAddressID :one

SELECT address_id FROM address WHERE addr = $1
`

// Layer-1 (blockchain infrastructure) queries.
// Converted from hand-written SQL in internal/store; the sqlc-generated code
// lives in internal/store/sqlcgen. See sqlc.yaml.
func (q *Queries) GetAddressID(ctx context.Context, addr string) (int64, error) {
	row := q.db.QueryRow(ctx, getAddressID, addr)
	var address_id int64
	err := row.Scan(&address_id)
	return address_id, err
}

const getBlockByHash = `-- name: GetBlockByHash :one
SELECT block_num, num_tx, ts, block_hash, parent_hash
FROM block
WHERE block_hash = $1
`

type GetBlockByHashRow struct {
	BlockNum   int64              `json:"block_num"`
	NumTx      *int64             `json:"num_tx"`
	Ts         pgtype.Timestamptz `json:"ts"`
	BlockHash  string             `json:"block_hash"`
	ParentHash string             `json:"parent_hash"`
}

func (q *Queries) GetBlockByHash(ctx context.Context, blockHash string) (GetBlockByHashRow, error) {
	row := q.db.QueryRow(ctx, getBlockByHash, blockHash)
	var i GetBlockByHashRow
	err := row.Scan(
		&i.BlockNum,
		&i.NumTx,
		&i.Ts,
		&i.BlockHash,
		&i.ParentHash,
	)
	return i, err
}

const getEventLogByTxAndIndex = `-- name: GetEventLogByTxAndIndex :one
SELECT id FROM evt_log WHERE tx_id = $1 AND log_index = $2
`

type GetEventLogByTxAndIndexParams struct {
	TxID     int64 `json:"tx_id"`
	LogIndex int32 `json:"log_index"`
}

func (q *Queries) GetEventLogByTxAndIndex(ctx context.Context, arg GetEventLogByTxAndIndexParams) (int64, error) {
	row := q.db.QueryRow(ctx, getEventLogByTxAndIndex, arg.TxID, arg.LogIndex)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLastBlockNum = `-- name: GetLastBlockNum :one
SELECT block_num FROM last_block LIMIT 1
`

func (q *Queries) GetLastBlockNum(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getLastBlockNum)
	var block_num int64
	err := row.Scan(&block_num)
	return block_num, err
}

const getTransactionID = `-- name: GetTransactionID :one
SELECT id FROM transaction WHERE tx_hash = $1
`

func (q *Queries) GetTransactionID(ctx context.Context, txHash string) (int64, error) {
	row := q.db.QueryRow(ctx, getTransactionID, txHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAddress = `-- name: InsertAddress :one
INSERT INTO address (block_num, tx_id, addr)
VALUES ($1, $2, $3)
ON CONFLICT (addr) DO UPDATE SET addr = EXCLUDED.addr
RETURNING address_id
`

type InsertAddressParams struct {
	BlockNum int64  `json:"block_num"`
	TxID     int64  `json:"tx_id"`
	Addr     string `json:"addr"`
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAddress, arg.BlockNum, arg.TxID, arg.Addr)
	var address_id int64
	err := row.Scan(&address_id)
	return address_id, err
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO block (block_num, num_tx, ts, block_hash, parent_hash)
VALUES ($1, $2, TO_TIMESTAMP($3), $4, $5)
`

type InsertBlockParams struct {
	BlockNum    int64   `json:"block_num"`
	NumTx       *int64  `json:"num_tx"`
	ToTimestamp float64 `json:"to_timestamp"`
	BlockHash   string  `json:"block_hash"`
	ParentHash  string  `json:"parent_hash"`
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock,
		arg.BlockNum,
		arg.NumTx,
		arg.ToTimestamp,
		arg.BlockHash,
		arg.ParentHash,
	)
	return err
}

const setLastBlockNum = `-- name: SetLastBlockNum :exec
UPDATE last_block SET block_num = $1
`

func (q *Queries) SetLastBlockNum(ctx context.Context, blockNum int64) error {
	_, err := q.db.Exec(ctx, setLastBlockNum, blockNum)
	return err
}
