// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AbiEvent struct {
	ID        int64   `json:"id"`
	Signature *string `json:"signature"`
	EvtName   string  `json:"evt_name"`
	Contracts string  `json:"contracts"`
}

type AbiFunc struct {
	ID        int64   `json:"id"`
	Signature *string `json:"signature"`
	FuncName  string  `json:"func_name"`
	Contracts string  `json:"contracts"`
}

type Address struct {
	AddressID int64  `json:"address_id"`
	BlockNum  int64  `json:"block_num"`
	TxID      int64  `json:"tx_id"`
	Addr      string `json:"addr"`
}

type ArchBlock struct {
	BlockNum   int64              `json:"block_num"`
	NumTx      *int64             `json:"num_tx"`
	Ts         pgtype.Timestamptz `json:"ts"`
	CashFlow   pgtype.Numeric     `json:"cash_flow"`
	BlockHash  string             `json:"block_hash"`
	ParentHash string             `json:"parent_hash"`
}

type ArchEvtlog struct {
	BlockNum     int64  `json:"block_num"`
	EvtID        *int64 `json:"evt_id"`
	LogIndex     int32  `json:"log_index"`
	TxHash       string `json:"tx_hash"`
	ContractAddr string `json:"contract_addr"`
	Topic0Sig    string `json:"topic0_sig"`
	LogRlp       []byte `json:"log_rlp"`
}

type ArchTx struct {
	BlockNum    int64          `json:"block_num"`
	FromAid     *int64         `json:"from_aid"`
	ToAid       *int64         `json:"to_aid"`
	GasUsed     *int64         `json:"gas_used"`
	TxIndex     *int32         `json:"tx_index"`
	NumLogs     *int32         `json:"num_logs"`
	CtrctCreate *bool          `json:"ctrct_create"`
	Value       pgtype.Numeric `json:"value"`
	GasPrice    pgtype.Numeric `json:"gas_price"`
	TxHash      string         `json:"tx_hash"`
	InputSig    *string        `json:"input_sig"`
}

type Block struct {
	BlockNum   int64              `json:"block_num"`
	NumTx      *int64             `json:"num_tx"`
	Ts         pgtype.Timestamptz `json:"ts"`
	CashFlow   pgtype.Numeric     `json:"cash_flow"`
	BlockHash  string             `json:"block_hash"`
	ParentHash string             `json:"parent_hash"`
}

type CgAdmActtime struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewAtime    pgtype.Numeric     `json:"new_atime"`
}

type CgAdmAdminChanged struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	OldAdminAid int64              `json:"old_admin_aid"`
	NewAdminAid int64              `json:"new_admin_aid"`
}

type CgAdmBaseUriC struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewUri      string             `json:"new_uri"`
}

type CgAdmCharityPcent struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	Percentage  pgtype.Numeric     `json:"percentage"`
}

type CgAdmCharityWallet struct {
	ID            int64              `json:"id"`
	EvtlogID      *int64             `json:"evtlog_id"`
	BlockNum      int64              `json:"block_num"`
	TxID          int64              `json:"tx_id"`
	TimeStamp     pgtype.Timestamptz `json:"time_stamp"`
	ContractAid   int64              `json:"contract_aid"`
	NewCharityAid int64              `json:"new_charity_aid"`
}

type CgAdmChronoPcent struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	Percentage  pgtype.Numeric     `json:"percentage"`
}

type CgAdmCossigAddr struct {
	ID           int64              `json:"id"`
	EvtlogID     *int64             `json:"evtlog_id"`
	BlockNum     int64              `json:"block_num"`
	TxID         int64              `json:"tx_id"`
	TimeStamp    pgtype.Timestamptz `json:"time_stamp"`
	ContractAid  int64              `json:"contract_aid"`
	NewCossigAid int64              `json:"new_cossig_aid"`
}

type CgAdmCostokAddr struct {
	ID           int64              `json:"id"`
	EvtlogID     *int64             `json:"evtlog_id"`
	BlockNum     int64              `json:"block_num"`
	TxID         int64              `json:"tx_id"`
	TimeStamp    pgtype.Timestamptz `json:"time_stamp"`
	ContractAid  int64              `json:"contract_aid"`
	NewCostokAid int64              `json:"new_costok_aid"`
}

type CgAdmCstAuclen struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewLen      pgtype.Numeric     `json:"new_len"`
}

type CgAdmCstAuclenChgDiv struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewLen      pgtype.Numeric     `json:"new_len"`
}

type CgAdmCstMinLimit struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	MinLimit    pgtype.Numeric     `json:"min_limit"`
}

type CgAdmErc20Reward struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewReward   pgtype.Numeric     `json:"new_reward"`
}

type CgAdmErcRwdMul struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewReward   pgtype.Numeric     `json:"new_reward"`
}

type CgAdmEthAucEndprice struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewLen      pgtype.Numeric     `json:"new_len"`
}

type CgAdmEthAuclen struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewLen      pgtype.Numeric     `json:"new_len"`
}

type CgAdmInisecprize struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewInisec   pgtype.Numeric     `json:"new_inisec"`
}

type CgAdmInitialized struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	Version     int64              `json:"version"`
}

type CgAdmMainPrizePcent struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	Percentage  pgtype.Numeric     `json:"percentage"`
}

type CgAdmMarketingAddr struct {
	ID              int64              `json:"id"`
	EvtlogID        *int64             `json:"evtlog_id"`
	BlockNum        int64              `json:"block_num"`
	TxID            int64              `json:"tx_id"`
	TimeStamp       pgtype.Timestamptz `json:"time_stamp"`
	ContractAid     int64              `json:"contract_aid"`
	NewMarketingAid int64              `json:"new_marketing_aid"`
}

type CgAdmMktReward struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewReward   pgtype.Numeric     `json:"new_reward"`
}

type CgAdmMsgLen struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewLength   pgtype.Numeric     `json:"new_length"`
}

type CgAdmOwnership struct {
	ID           int64              `json:"id"`
	EvtlogID     *int64             `json:"evtlog_id"`
	BlockNum     int64              `json:"block_num"`
	TxID         int64              `json:"tx_id"`
	TimeStamp    pgtype.Timestamptz `json:"time_stamp"`
	ContractAid  int64              `json:"contract_aid"`
	PrevOwnerAid int64              `json:"prev_owner_aid"`
	NewOwnerAid  int64              `json:"new_owner_aid"`
	ContractCode int32              `json:"contract_code"`
}

type CgAdmPriceInc struct {
	ID               int64              `json:"id"`
	EvtlogID         *int64             `json:"evtlog_id"`
	BlockNum         int64              `json:"block_num"`
	TxID             int64              `json:"tx_id"`
	TimeStamp        pgtype.Timestamptz `json:"time_stamp"`
	ContractAid      int64              `json:"contract_aid"`
	NewPriceIncrease pgtype.Numeric     `json:"new_price_increase"`
}

type CgAdmPrizeMicrosec struct {
	ID              int64              `json:"id"`
	EvtlogID        *int64             `json:"evtlog_id"`
	BlockNum        int64              `json:"block_num"`
	TxID            int64              `json:"tx_id"`
	TimeStamp       pgtype.Timestamptz `json:"time_stamp"`
	ContractAid     int64              `json:"contract_aid"`
	NewMicroseconds pgtype.Numeric     `json:"new_microseconds"`
}

type CgAdmPrizesWalletAddr struct {
	ID           int64              `json:"id"`
	EvtlogID     *int64             `json:"evtlog_id"`
	BlockNum     int64              `json:"block_num"`
	TxID         int64              `json:"tx_id"`
	TimeStamp    pgtype.Timestamptz `json:"time_stamp"`
	ContractAid  int64              `json:"contract_aid"`
	NewWalletAid int64              `json:"new_wallet_aid"`
}

type CgAdmRafEthBidding struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NumWinners  pgtype.Numeric     `json:"num_winners"`
}

type CgAdmRafNftBidding struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NumWinners  pgtype.Numeric     `json:"num_winners"`
}

type CgAdmRafNftStakingRwalk struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NumWinners  pgtype.Numeric     `json:"num_winners"`
}

type CgAdmRafflePcent struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	Percentage  pgtype.Numeric     `json:"percentage"`
}

type CgAdmRwalkAddr struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewRwalkAid int64              `json:"new_rwalk_aid"`
}

type CgAdmScriptUrl struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewUrl      string             `json:"new_url"`
}

type CgAdmStakePcent struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	Percentage  pgtype.Numeric     `json:"percentage"`
}

type CgAdmStakingCstAddr struct {
	ID            int64              `json:"id"`
	EvtlogID      *int64             `json:"evtlog_id"`
	BlockNum      int64              `json:"block_num"`
	TxID          int64              `json:"tx_id"`
	TimeStamp     pgtype.Timestamptz `json:"time_stamp"`
	ContractAid   int64              `json:"contract_aid"`
	NewStakingAid int64              `json:"new_staking_aid"`
}

type CgAdmStakingRwalkAddr struct {
	ID            int64              `json:"id"`
	EvtlogID      *int64             `json:"evtlog_id"`
	BlockNum      int64              `json:"block_num"`
	TxID          int64              `json:"tx_id"`
	TimeStamp     pgtype.Timestamptz `json:"time_stamp"`
	ContractAid   int64              `json:"contract_aid"`
	NewStakingAid int64              `json:"new_staking_aid"`
}

type CgAdmTimeInc struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewTimeInc  pgtype.Numeric     `json:"new_time_inc"`
}

type CgAdmTimeoutClaimprize struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewTimeout  int64              `json:"new_timeout"`
}

type CgAdmTimeoutWithdraw struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewTimeout  int64              `json:"new_timeout"`
}

type CgAdmTreasurerAddr struct {
	ID              int64              `json:"id"`
	EvtlogID        *int64             `json:"evtlog_id"`
	BlockNum        int64              `json:"block_num"`
	TxID            int64              `json:"tx_id"`
	TimeStamp       pgtype.Timestamptz `json:"time_stamp"`
	ContractAid     int64              `json:"contract_aid"`
	NewTreasurerAid int64              `json:"new_treasurer_aid"`
}

type CgAdmUpgraded struct {
	ID                int64              `json:"id"`
	EvtlogID          *int64             `json:"evtlog_id"`
	BlockNum          int64              `json:"block_num"`
	TxID              int64              `json:"tx_id"`
	TimeStamp         pgtype.Timestamptz `json:"time_stamp"`
	ContractAid       int64              `json:"contract_aid"`
	ImplementationAid int64              `json:"implementation_aid"`
}

type CgBannedBid struct {
	ID        int64  `json:"id"`
	BidID     int64  `json:"bid_id"`
	UserAddr  string `json:"user_addr"`
	CreatedAt int64  `json:"created_at"`
}

type CgBid struct {
	ID                      int64              `json:"id"`
	EvtlogID                *int64             `json:"evtlog_id"`
	BlockNum                int64              `json:"block_num"`
	TxID                    int64              `json:"tx_id"`
	TimeStamp               pgtype.Timestamptz `json:"time_stamp"`
	ContractAid             int64              `json:"contract_aid"`
	BidderAid               int64              `json:"bidder_aid"`
	RwalkNftID              int64              `json:"rwalk_nft_id"`
	RoundNum                int64              `json:"round_num"`
	BidType                 int16              `json:"bid_type"`
	BidPosition             int64              `json:"bid_position"`
	PrizeTime               pgtype.Timestamptz `json:"prize_time"`
	EthPrice                pgtype.Numeric     `json:"eth_price"`
	CstPrice                pgtype.Numeric     `json:"cst_price"`
	CstReward               pgtype.Numeric     `json:"cst_reward"`
	BidCstRewardAmount      pgtype.Numeric     `json:"bid_cst_reward_amount"`
	CstDutchAuctionDuration pgtype.Numeric     `json:"cst_dutch_auction_duration"`
	Msg                     *string            `json:"msg"`
}

type CgBidder struct {
	BidderAid     int64          `json:"bidder_aid"`
	NumBids       *int64         `json:"num_bids"`
	MaxBid        pgtype.Numeric `json:"max_bid"`
	TokensMinted  pgtype.Numeric `json:"tokens_minted"`
	TotalEthSpent pgtype.Numeric `json:"total_eth_spent"`
	TotalCstSpent pgtype.Numeric `json:"total_cst_spent"`
}

type CgCharityReceiverChanged struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	CharityAid  int64              `json:"charity_aid"`
}

type CgChronoWarriorPrize struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	WinnerAid   int64              `json:"winner_aid"`
	RoundNum    int64              `json:"round_num"`
	WinnerIndex int64              `json:"winner_index"`
	EthAmount   pgtype.Numeric     `json:"eth_amount"`
	CstAmount   pgtype.Numeric     `json:"cst_amount"`
	NftID       int64              `json:"nft_id"`
}

type CgContract struct {
	CosmicGameAddr         string `json:"cosmic_game_addr"`
	CosmicSignatureAddr    string `json:"cosmic_signature_addr"`
	CosmicTokenAddr        string `json:"cosmic_token_addr"`
	CosmicDaoAddr          string `json:"cosmic_dao_addr"`
	CharityWalletAddr      string `json:"charity_wallet_addr"`
	PrizesWalletAddr       string `json:"prizes_wallet_addr"`
	RandomWalkAddr         string `json:"random_walk_addr"`
	StakingWalletCstAddr   string `json:"staking_wallet_cst_addr"`
	StakingWalletRwalkAddr string `json:"staking_wallet_rwalk_addr"`
	MarketingWalletAddr    string `json:"marketing_wallet_addr"`
	ImplementationAddr     string `json:"implementation_addr"`
}

type CgCostokOwner struct {
	OwnerAid   int64          `json:"owner_aid"`
	CurBalance pgtype.Numeric `json:"cur_balance"`
}

type CgDelayDuration struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	NewValue    pgtype.Numeric     `json:"new_value"`
}

type CgDonatedNftClaimed struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	RoundNum    int64              `json:"round_num"`
	Idx         int64              `json:"idx"`
	TokenAid    int64              `json:"token_aid"`
	WinnerAid   int64              `json:"winner_aid"`
	TokenID     pgtype.Numeric     `json:"token_id"`
}

type CgDonatedTokClaimed struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	RoundNum    int64              `json:"round_num"`
	Idx         int64              `json:"idx"`
	TokenAid    int64              `json:"token_aid"`
	WinnerAid   int64              `json:"winner_aid"`
	Amount      pgtype.Numeric     `json:"amount"`
}

type CgDonationJson struct {
	RecordID int64   `json:"record_id"`
	Data     *string `json:"data"`
}

type CgDonationReceived struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	DonorAid    int64              `json:"donor_aid"`
	Amount      pgtype.Numeric     `json:"amount"`
	RoundNum    int64              `json:"round_num"`
}

type CgDonationSent struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	CharityAid  int64              `json:"charity_aid"`
	Amount      pgtype.Numeric     `json:"amount"`
}

type CgDonor struct {
	DonorAid        int64          `json:"donor_aid"`
	CountDonations  *int64         `json:"count_donations"`
	TotalEthDonated pgtype.Numeric `json:"total_eth_donated"`
}

type CgEndurancePrize struct {
	ID            int64              `json:"id"`
	EvtlogID      *int64             `json:"evtlog_id"`
	BlockNum      int64              `json:"block_num"`
	TxID          int64              `json:"tx_id"`
	TimeStamp     pgtype.Timestamptz `json:"time_stamp"`
	ContractAid   int64              `json:"contract_aid"`
	WinnerAid     int64              `json:"winner_aid"`
	RoundNum      int64              `json:"round_num"`
	Erc721TokenID int64              `json:"erc721_token_id"`
	Erc20Amount   pgtype.Numeric     `json:"erc20_amount"`
}

type CgErc20Donation struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	RoundNum    int64              `json:"round_num"`
	DonorAid    int64              `json:"donor_aid"`
	TokenAid    int64              `json:"token_aid"`
	Amount      pgtype.Numeric     `json:"amount"`
	BidID       int64              `json:"bid_id"`
}

type CgErc20DonationStat struct {
	TokenAid    int64          `json:"token_aid"`
	RoundNum    int64          `json:"round_num"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
	Claimed     *bool          `json:"claimed"`
	WinnerAid   *int64         `json:"winner_aid"`
}

type CgErc20TransfErr struct {
	ID             int64              `json:"id"`
	EvtlogID       *int64             `json:"evtlog_id"`
	BlockNum       int64              `json:"block_num"`
	TxID           int64              `json:"tx_id"`
	TimeStamp      pgtype.Timestamptz `json:"time_stamp"`
	ContractAid    int64              `json:"contract_aid"`
	DestinationAid int64              `json:"destination_aid"`
	Amount         pgtype.Numeric     `json:"amount"`
}

type CgErc20Transfer struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	Value       pgtype.Numeric     `json:"value"`
	FromAid     int64              `json:"from_aid"`
	ToAid       int64              `json:"to_aid"`
	Otype       int16              `json:"otype"`
}

type CgErc721Transfer struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	TokenID     int64              `json:"token_id"`
	FromAid     int64              `json:"from_aid"`
	ToAid       int64              `json:"to_aid"`
	Otype       int16              `json:"otype"`
}

type CgEthDonated struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	DonorAid    int64              `json:"donor_aid"`
	RoundNum    int64              `json:"round_num"`
	Amount      pgtype.Numeric     `json:"amount"`
}

type CgEthDonatedWi struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	DonorAid    int64              `json:"donor_aid"`
	RoundNum    int64              `json:"round_num"`
	RecordID    int64              `json:"record_id"`
	Amount      pgtype.Numeric     `json:"amount"`
}

type CgFirstBid struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	RoundNum    int64              `json:"round_num"`
	StartTs     int64              `json:"start_ts"`
}

type CgFundTransfErr struct {
	ID             int64              `json:"id"`
	EvtlogID       *int64             `json:"evtlog_id"`
	BlockNum       int64              `json:"block_num"`
	TxID           int64              `json:"tx_id"`
	TimeStamp      pgtype.Timestamptz `json:"time_stamp"`
	ContractAid    int64              `json:"contract_aid"`
	DestinationAid int64              `json:"destination_aid"`
	Amount         pgtype.Numeric     `json:"amount"`
}

type CgFundsToCharity struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	CharityAid  int64              `json:"charity_aid"`
	Amount      pgtype.Numeric     `json:"amount"`
}

type CgGlobStat struct {
	NumVolDonations               *int64         `json:"num_vol_donations"`
	VolDonationsTotal             pgtype.Numeric `json:"vol_donations_total"`
	CgDonationsTotal              pgtype.Numeric `json:"cg_donations_total"`
	NumCgDonations                *int64         `json:"num_cg_donations"`
	DirectDonations               pgtype.Numeric `json:"direct_donations"`
	NumDirectDonations            *int64         `json:"num_direct_donations"`
	SumWithdrawals                pgtype.Numeric `json:"sum_withdrawals"`
	NumWithdrawals                *int64         `json:"num_withdrawals"`
	NumBids                       *int64         `json:"num_bids"`
	NumWins                       *int64         `json:"num_wins"`
	NumRwalkUsed                  *int64         `json:"num_rwalk_used"`
	NumMints                      *int64         `json:"num_mints"`
	CurNumBids                    *int64         `json:"cur_num_bids"`
	NumBidsCst                    *int64         `json:"num_bids_cst"`
	TotalRaffleEthDeposits        pgtype.Numeric `json:"total_raffle_eth_deposits"`
	TotalRaffleEthWithdrawn       pgtype.Numeric `json:"total_raffle_eth_withdrawn"`
	TotalChronoWarriorEthDeposits pgtype.Numeric `json:"total_chrono_warrior_eth_deposits"`
	TotalCstGivenInPrizes         pgtype.Numeric `json:"total_cst_given_in_prizes"`
	CstRewardForBidding           pgtype.Numeric `json:"cst_reward_for_bidding"`
	TotalNftDonated               *int64         `json:"total_nft_donated"`
	TotalErc20Donations           *int64         `json:"total_erc20_donations"`
	TotalCstConsumed              pgtype.Numeric `json:"total_cst_consumed"`
	TotalMktRewards               pgtype.Numeric `json:"total_mkt_rewards"`
	NumMktRewards                 *int64         `json:"num_mkt_rewards"`
}

type CgLastcstPrize struct {
	ID            int64              `json:"id"`
	EvtlogID      *int64             `json:"evtlog_id"`
	BlockNum      int64              `json:"block_num"`
	TxID          int64              `json:"tx_id"`
	TimeStamp     pgtype.Timestamptz `json:"time_stamp"`
	ContractAid   int64              `json:"contract_aid"`
	WinnerAid     int64              `json:"winner_aid"`
	RoundNum      int64              `json:"round_num"`
	Erc721TokenID int64              `json:"erc721_token_id"`
	Erc20Amount   pgtype.Numeric     `json:"erc20_amount"`
}

type CgMintEvent struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	OwnerAid    int64              `json:"owner_aid"`
	TokenID     int64              `json:"token_id"`
	CurOwnerAid int64              `json:"cur_owner_aid"`
	RoundNum    int64              `json:"round_num"`
	Seed        string             `json:"seed"`
	TokenName   *string            `json:"token_name"`
}

type CgMktReward struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	Amount      pgtype.Numeric     `json:"amount"`
	MarketerAid int64              `json:"marketer_aid"`
}

type CgNftDonation struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	RoundNum    int64              `json:"round_num"`
	DonorAid    int64              `json:"donor_aid"`
	TokenAid    int64              `json:"token_aid"`
	TokenID     int64              `json:"token_id"`
	Idx         int64              `json:"idx"`
	BidID       int64              `json:"bid_id"`
	TokenUri    string             `json:"token_uri"`
}

type CgNftStakedCst struct {
	ID              int64              `json:"id"`
	EvtlogID        *int64             `json:"evtlog_id"`
	BlockNum        int64              `json:"block_num"`
	TxID            int64              `json:"tx_id"`
	TimeStamp       pgtype.Timestamptz `json:"time_stamp"`
	ContractAid     int64              `json:"contract_aid"`
	ActionID        int64              `json:"action_id"`
	TokenID         int64              `json:"token_id"`
	RoundNum        *int64             `json:"round_num"`
	NumStakedNfts   int64              `json:"num_staked_nfts"`
	RewardPerStaker pgtype.Numeric     `json:"reward_per_staker"`
	StakerAid       int64              `json:"staker_aid"`
	Claimed         *bool              `json:"claimed"`
}

type CgNftStakedRwalk struct {
	ID            int64              `json:"id"`
	EvtlogID      *int64             `json:"evtlog_id"`
	BlockNum      int64              `json:"block_num"`
	TxID          int64              `json:"tx_id"`
	TimeStamp     pgtype.Timestamptz `json:"time_stamp"`
	ContractAid   int64              `json:"contract_aid"`
	ActionID      int64              `json:"action_id"`
	TokenID       int64              `json:"token_id"`
	RoundNum      *int64             `json:"round_num"`
	NumStakedNfts int64              `json:"num_staked_nfts"`
	StakerAid     int64              `json:"staker_aid"`
}

type CgNftStat struct {
	ContractAid int64  `json:"contract_aid"`
	NumDonated  *int64 `json:"num_donated"`
}

type CgNftUnstakedCst struct {
	ID            int64              `json:"id"`
	EvtlogID      *int64             `json:"evtlog_id"`
	BlockNum      int64              `json:"block_num"`
	TxID          int64              `json:"tx_id"`
	TimeStamp     pgtype.Timestamptz `json:"time_stamp"`
	ContractAid   int64              `json:"contract_aid"`
	ActionID      int64              `json:"action_id"`
	ActionCounter int64              `json:"action_counter"`
	TokenID       int64              `json:"token_id"`
	NumStakedNfts int64              `json:"num_staked_nfts"`
	RoundNum      *int64             `json:"round_num"`
	StakerAid     int64              `json:"staker_aid"`
	Reward        pgtype.Numeric     `json:"reward"`
	RewardPerTok  pgtype.Numeric     `json:"reward_per_tok"`
}

type CgNftUnstakedRwalk struct {
	ID            int64              `json:"id"`
	EvtlogID      *int64             `json:"evtlog_id"`
	BlockNum      int64              `json:"block_num"`
	TxID          int64              `json:"tx_id"`
	TimeStamp     pgtype.Timestamptz `json:"time_stamp"`
	ContractAid   int64              `json:"contract_aid"`
	ActionID      int64              `json:"action_id"`
	TokenID       int64              `json:"token_id"`
	RoundNum      *int64             `json:"round_num"`
	NumStakedNfts int64              `json:"num_staked_nfts"`
	StakerAid     int64              `json:"staker_aid"`
}

type CgPrize struct {
	RoundNum    int64 `json:"round_num"`
	WinnerIndex int64 `json:"winner_index"`
	Ptype       int16 `json:"ptype"`
}

type CgPrizeClaim struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	RoundNum    int64              `json:"round_num"`
	WinnerAid   int64              `json:"winner_aid"`
	TokenID     int64              `json:"token_id"`
	Timeout     int64              `json:"timeout"`
	Amount      pgtype.Numeric     `json:"amount"`
	CstAmount   pgtype.Numeric     `json:"cst_amount"`
}

type CgPrizeDeposit struct {
	ID           int64              `json:"id"`
	EvtlogID     *int64             `json:"evtlog_id"`
	BlockNum     int64              `json:"block_num"`
	TxID         int64              `json:"tx_id"`
	TimeStamp    pgtype.Timestamptz `json:"time_stamp"`
	ContractAid  int64              `json:"contract_aid"`
	WinnerAid    int64              `json:"winner_aid"`
	RoundNum     int64              `json:"round_num"`
	WinnerIndex  int64              `json:"winner_index"`
	Amount       pgtype.Numeric     `json:"amount"`
	Claimed      *bool              `json:"claimed"`
	WithdrawalID *int64             `json:"withdrawal_id"`
}

type CgPrizeWithdrawal struct {
	ID             int64              `json:"id"`
	EvtlogID       *int64             `json:"evtlog_id"`
	BlockNum       int64              `json:"block_num"`
	TxID           int64              `json:"tx_id"`
	TimeStamp      pgtype.Timestamptz `json:"time_stamp"`
	ContractAid    int64              `json:"contract_aid"`
	RoundNum       int64              `json:"round_num"`
	WinnerAid      int64              `json:"winner_aid"`
	BeneficiaryAid int64              `json:"beneficiary_aid"`
	Amount         pgtype.Numeric     `json:"amount"`
}

type CgProcStatus struct {
	LastEvtID    *int64 `json:"last_evt_id"`
	LastBlockNum *int64 `json:"last_block_num"`
}

type CgRaffleEthPrize struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	WinnerAid   int64              `json:"winner_aid"`
	RoundNum    int64              `json:"round_num"`
	WinnerIdx   int64              `json:"winner_idx"`
	Amount      pgtype.Numeric     `json:"amount"`
}

type CgRaffleNftPrize struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	WinnerAid   int64              `json:"winner_aid"`
	RoundNum    int64              `json:"round_num"`
	TokenID     int64              `json:"token_id"`
	WinnerIdx   int64              `json:"winner_idx"`
	CstAmount   pgtype.Numeric     `json:"cst_amount"`
	IsRwalk     bool               `json:"is_rwalk"`
	IsStaker    bool               `json:"is_staker"`
}

type CgRaffleNftWinnerStat struct {
	WinnerAid int64  `json:"winner_aid"`
	NumWon    *int64 `json:"num_won"`
}

type CgRaffleWinnerStat struct {
	WinnerAid     int64          `json:"winner_aid"`
	AmountSum     pgtype.Numeric `json:"amount_sum"`
	WithdrawalSum pgtype.Numeric `json:"withdrawal_sum"`
	RafflesCount  *int64         `json:"raffles_count"`
}

type CgRoundStat struct {
	RoundNum                   int64              `json:"round_num"`
	TotalBids                  *int64             `json:"total_bids"`
	TotalNftDonated            *int64             `json:"total_nft_donated"`
	NumErc20Donations          *int64             `json:"num_erc20_donations"`
	TotalRaffleEthDeposits     pgtype.Numeric     `json:"total_raffle_eth_deposits"`
	ChronoWarriorPrizeEth      pgtype.Numeric     `json:"chrono_warrior_prize_eth"`
	TotalCstPaidInPrizes       pgtype.Numeric     `json:"total_cst_paid_in_prizes"`
	TotalNftsMinted            *int64             `json:"total_nfts_minted"`
	NumContractsDonatedErc20   *int64             `json:"num_contracts_donated_erc20"`
	TotalRaffleNfts            *int64             `json:"total_raffle_nfts"`
	DonationsRoundTotal        pgtype.Numeric     `json:"donations_round_total"`
	DonationsRoundCount        *int64             `json:"donations_round_count"`
	TotalEthInBids             pgtype.Numeric     `json:"total_eth_in_bids"`
	TotalCstInBids             pgtype.Numeric     `json:"total_cst_in_bids"`
	ParamWindowStartTime       pgtype.Timestamptz `json:"param_window_start_time"`
	ActivationTime             pgtype.Timestamptz `json:"activation_time"`
	ParamWindowDurationSeconds *int64             `json:"param_window_duration_seconds"`
	RoundStartTime             pgtype.Timestamptz `json:"round_start_time"`
	RoundEndTime               pgtype.Timestamptz `json:"round_end_time"`
	RoundDurationSeconds       *int64             `json:"round_duration_seconds"`
}

type CgStReward struct {
	StakerAid int64          `json:"staker_aid"`
	ActionID  int64          `json:"action_id"`
	TokenID   int64          `json:"token_id"`
	DepositID int64          `json:"deposit_id"`
	RoundNum  int64          `json:"round_num"`
	Reward    pgtype.Numeric `json:"reward"`
	Collected *bool          `json:"collected"`
	IsUnstake *bool          `json:"is_unstake"`
}

type CgStakeStatsCst struct {
	TotalTokensStaked    *int64         `json:"total_tokens_staked"`
	TotalRewardAmount    pgtype.Numeric `json:"total_reward_amount"`
	TotalUnclaimedReward pgtype.Numeric `json:"total_unclaimed_reward"`
	TotalNumStakers      *int64         `json:"total_num_stakers"`
	NumDeposits          *int64         `json:"num_deposits"`
	TotalModulo          pgtype.Numeric `json:"total_modulo"`
	NumCharityDeposits   *int64         `json:"num_charity_deposits"`
	TotalCharityAmount   pgtype.Numeric `json:"total_charity_amount"`
}

type CgStakeStatsRwalk struct {
	TotalTokensStaked *int64 `json:"total_tokens_staked"`
	TotalNumStakers   *int64 `json:"total_num_stakers"`
	TotalNftMints     *int64 `json:"total_nft_mints"`
}

type CgStakedTokenCst struct {
	StakerAid     int64 `json:"staker_aid"`
	TokenID       int64 `json:"token_id"`
	StakeActionID int64 `json:"stake_action_id"`
}

type CgStakedTokenCstReward struct {
	StakerAid         int64          `json:"staker_aid"`
	TokenID           int64          `json:"token_id"`
	StakeActionID     int64          `json:"stake_action_id"`
	AccumulatedReward pgtype.Numeric `json:"accumulated_reward"`
	ClaimedReward     pgtype.Numeric `json:"claimed_reward"`
}

type CgStakedTokenRwalk struct {
	StakerAid     int64 `json:"staker_aid"`
	TokenID       int64 `json:"token_id"`
	StakeActionID int64 `json:"stake_action_id"`
}

type CgStakerCst struct {
	StakerAid         int64          `json:"staker_aid"`
	TotalTokensStaked *int64         `json:"total_tokens_staked"`
	NumStakeActions   *int64         `json:"num_stake_actions"`
	NumUnstakeActions *int64         `json:"num_unstake_actions"`
	TotalReward       pgtype.Numeric `json:"total_reward"`
	UnclaimedReward   pgtype.Numeric `json:"unclaimed_reward"`
	NumTokensMinted   *int64         `json:"num_tokens_minted"`
}

type CgStakerDeposit struct {
	StakerAid       int64          `json:"staker_aid"`
	DepositID       int64          `json:"deposit_id"`
	TokensStaked    *int64         `json:"tokens_staked"`
	AmountDeposited pgtype.Numeric `json:"amount_deposited"`
	AmountToClaim   pgtype.Numeric `json:"amount_to_claim"`
}

type CgStakerRwalk struct {
	StakerAid         int64  `json:"staker_aid"`
	TotalTokensStaked *int64 `json:"total_tokens_staked"`
	NumStakeActions   *int64 `json:"num_stake_actions"`
	NumUnstakeActions *int64 `json:"num_unstake_actions"`
	NumTokensMinted   *int64 `json:"num_tokens_minted"`
}

type CgStakingEthDeposit struct {
	ID                  int64              `json:"id"`
	EvtlogID            *int64             `json:"evtlog_id"`
	BlockNum            int64              `json:"block_num"`
	TxID                int64              `json:"tx_id"`
	TimeStamp           pgtype.Timestamptz `json:"time_stamp"`
	ContractAid         int64              `json:"contract_aid"`
	RoundNum            int64              `json:"round_num"`
	DepositTime         pgtype.Timestamptz `json:"deposit_time"`
	DepositID           int64              `json:"deposit_id"`
	NumStakedNfts       int64              `json:"num_staked_nfts"`
	AccumulatedNfts     *int64             `json:"accumulated_nfts"`
	DepositAmount       pgtype.Numeric     `json:"deposit_amount"`
	AccumulatedAmount   pgtype.Numeric     `json:"accumulated_amount"`
	AmountPerToken      pgtype.Numeric     `json:"amount_per_token"`
	AccumulatedPerToken pgtype.Numeric     `json:"accumulated_per_token"`
	Modulo              pgtype.Numeric     `json:"modulo"`
	AccumModulo         pgtype.Numeric     `json:"accum_modulo"`
}

type CgTokenName struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	TokenID     int64              `json:"token_id"`
	TokenName   string             `json:"token_name"`
}

type CgTransferStat struct {
	UserAid            int64  `json:"user_aid"`
	Erc20NumTransfers  *int64 `json:"erc20_num_transfers"`
	Erc721NumTransfers *int64 `json:"erc721_num_transfers"`
}

type CgWinner struct {
	WinnerAid     int64          `json:"winner_aid"`
	MaxWinAmount  pgtype.Numeric `json:"max_win_amount"`
	PrizesCount   *int64         `json:"prizes_count"`
	PrizesSum     pgtype.Numeric `json:"prizes_sum"`
	TokensCount   *int64         `json:"tokens_count"`
	Erc20Count    *int64         `json:"erc20_count"`
	Erc721Count   *int64         `json:"erc721_count"`
	UnclaimedNfts *int64         `json:"unclaimed_nfts"`
}

type ChainReorg struct {
	ID       int64  `json:"id"`
	BlockNum int64  `json:"block_num"`
	Hash     string `json:"hash"`
}

type ContractAddress struct {
	UploadBlock   *int64  `json:"upload_block"`
	ChainID       *int64  `json:"chain_id"`
	Augur         *string `json:"augur"`
	AugurTrading  *string `json:"augur_trading"`
	ProfitLoss    *string `json:"profit_loss"`
	DaiCash       *string `json:"dai_cash"`
	ZeroxTrade    *string `json:"zerox_trade"`
	ZeroxXchg     *string `json:"zerox_xchg"`
	RepToken      *string `json:"rep_token"`
	WalletReg     *string `json:"wallet_reg"`
	WalletReg2    *string `json:"wallet_reg2"`
	FillOrder     *string `json:"fill_order"`
	EthXchg       *string `json:"eth_xchg"`
	ShareToken    *string `json:"share_token"`
	Universe      *string `json:"universe"`
	CreateOrder   *string `json:"create_order"`
	LegRepToken   *string `json:"leg_rep_token"`
	BuyPartTok    *string `json:"buy_part_tok"`
	RedeemStake   *string `json:"redeem_stake"`
	WarpSync      *string `json:"warp_sync"`
	HotLoading    *string `json:"hot_loading"`
	Affiliates    *string `json:"affiliates"`
	AffiliateVal  *string `json:"affiliate_val"`
	Ctime         *string `json:"ctime"`
	CancelOrder   *string `json:"cancel_order"`
	Orders        *string `json:"orders"`
	SimTrade      *string `json:"sim_trade"`
	Trade         *string `json:"trade"`
	OiCash        *string `json:"oi_cash"`
	UniswapV2Fact *string `json:"uniswap_v2_fact"`
	UniswapV2R2   *string `json:"uniswap_v2_r2"`
	AuditFunds    *string `json:"audit_funds"`
	Weth9         *string `json:"weth9"`
	Usdc          *string `json:"usdc"`
	Usdt          *string `json:"usdt"`
	RelayHubV2    *string `json:"relay_hub_v2"`
	AccountLoader *string `json:"account_loader"`
}

type EvtLog struct {
	ID          int64  `json:"id"`
	BlockNum    int64  `json:"block_num"`
	TxID        int64  `json:"tx_id"`
	ContractAid int64  `json:"contract_aid"`
	Topic0Sig   string `json:"topic0_sig"`
	LogIndex    int32  `json:"log_index"`
	LogRlp      []byte `json:"log_rlp"`
}

type EvtTopic struct {
	ID          int64   `json:"id"`
	BlockNum    int64   `json:"block_num"`
	TxID        int64   `json:"tx_id"`
	EvtlogID    int64   `json:"evtlog_id"`
	ContractAid int64   `json:"contract_aid"`
	Pos         int16   `json:"pos"`
	Value       *string `json:"value"`
}

type LastBlock struct {
	BlockNum int64 `json:"block_num"`
}

type RwContract struct {
	MarketplaceAddr *string `json:"marketplace_addr"`
	RandomwalkAddr  *string `json:"randomwalk_addr"`
}

type RwItemBought struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	OfferID     int64              `json:"offer_id"`
	SellerAid   int64              `json:"seller_aid"`
	BuyerAid    int64              `json:"buyer_aid"`
}

type RwMessagingStatus struct {
	LastTxID      *int64 `json:"last_tx_id"`
	LastEvtlogID  *int64 `json:"last_evtlog_id"`
	LastBlockNum  *int64 `json:"last_block_num"`
	LastTimestamp *int64 `json:"last_timestamp"`
}

type RwMintEvt struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	TokenID     int64              `json:"token_id"`
	OwnerAid    int64              `json:"owner_aid"`
	Seed        string             `json:"seed"`
	SeedNum     pgtype.Numeric     `json:"seed_num"`
	Price       pgtype.Numeric     `json:"price"`
}

type RwMktStat struct {
	ContractAid     int64          `json:"contract_aid"`
	TotalVol        pgtype.Numeric `json:"total_vol"`
	TotalNumTrades  *int64         `json:"total_num_trades"`
	TotalBuyOrders  *int64         `json:"total_buy_orders"`
	TotalSellOrders *int64         `json:"total_sell_orders"`
}

type RwNewOffer struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	RwalkAid    int64              `json:"rwalk_aid"`
	OfferID     int64              `json:"offer_id"`
	SellerAid   int64              `json:"seller_aid"`
	BuyerAid    int64              `json:"buyer_aid"`
	Otype       int16              `json:"otype"`
	TokenID     int64              `json:"token_id"`
	Active      *bool              `json:"active"`
	Price       pgtype.Numeric     `json:"price"`
	Profit      pgtype.Numeric     `json:"profit"`
}

type RwNotifStatus struct {
	LastTokenIDTweeter *int64  `json:"last_token_id_tweeter"`
	LastTokenIDDiscord *int64  `json:"last_token_id_discord"`
	MsgText            *string `json:"msg_text"`
}

type RwOfferCanceled struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	OfferID     int64              `json:"offer_id"`
}

type RwProcStatus struct {
	LastEvtID *int64 `json:"last_evt_id"`
	LastBlock *int64 `json:"last_block"`
}

type RwRankingMatch struct {
	ID        int64              `json:"id"`
	Nft1      int64              `json:"nft1"`
	Nft2      int64              `json:"nft2"`
	Nft1Won   bool               `json:"nft1_won"`
	VoterAid  *int64             `json:"voter_aid"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RwRankingVoteNonce struct {
	Nonce     string             `json:"nonce"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type RwStat struct {
	RwalkAid         int64          `json:"rwalk_aid"`
	TotalVol         pgtype.Numeric `json:"total_vol"`
	TotalNumTrades   *int64         `json:"total_num_trades"`
	TotalNumToks     *int64         `json:"total_num_toks"`
	TotalWithdrawals *int64         `json:"total_withdrawals"`
	MoneyAccumulated pgtype.Numeric `json:"money_accumulated"`
}

type RwToken struct {
	TokenID     int64          `json:"token_id"`
	RwalkAid    int64          `json:"rwalk_aid"`
	CurOwnerAid int64          `json:"cur_owner_aid"`
	SeedHex     *string        `json:"seed_hex"`
	SeedNum     pgtype.Numeric `json:"seed_num"`
	LastName    *string        `json:"last_name"`
	LastPrice   pgtype.Numeric `json:"last_price"`
	NumTrades   *int64         `json:"num_trades"`
	TotalVol    pgtype.Numeric `json:"total_vol"`
}

type RwTokenName struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	TokenID     int64              `json:"token_id"`
	NewName     *string            `json:"new_name"`
}

type RwTokenRanking struct {
	TokenID   int64              `json:"token_id"`
	Rating    float64            `json:"rating"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RwTransfer struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	TokenID     int64              `json:"token_id"`
	FromAid     int64              `json:"from_aid"`
	ToAid       int64              `json:"to_aid"`
	Otype       int16              `json:"otype"`
}

type RwUrank struct {
	Aid         int64          `json:"aid"`
	TotalTrades *int64         `json:"total_trades"`
	TopProfit   pgtype.Numeric `json:"top_profit"`
	TopTrades   pgtype.Numeric `json:"top_trades"`
	TopVolume   pgtype.Numeric `json:"top_volume"`
	Profit      pgtype.Numeric `json:"profit"`
	Volume      pgtype.Numeric `json:"volume"`
}

type RwUserRwtok struct {
	RwalkAid    int64          `json:"rwalk_aid"`
	UserAid     int64          `json:"user_aid"`
	TokenID     int64          `json:"token_id"`
	PriceBought pgtype.Numeric `json:"price_bought"`
}

type RwUserStat struct {
	RwalkAid         int64          `json:"rwalk_aid"`
	UserAid          int64          `json:"user_aid"`
	TotalVol         pgtype.Numeric `json:"total_vol"`
	TotalNumTrades   *int64         `json:"total_num_trades"`
	TotalNumToks     *int64         `json:"total_num_toks"`
	TotalWithdrawals *int64         `json:"total_withdrawals"`
	TotalProfit      pgtype.Numeric `json:"total_profit"`
}

type RwWithdrawal struct {
	ID          int64              `json:"id"`
	EvtlogID    *int64             `json:"evtlog_id"`
	BlockNum    int64              `json:"block_num"`
	TxID        int64              `json:"tx_id"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
	ContractAid int64              `json:"contract_aid"`
	Aid         int64              `json:"aid"`
	TokenID     int64              `json:"token_id"`
	Amount      pgtype.Numeric     `json:"amount"`
}

type Transaction struct {
	ID          int64          `json:"id"`
	BlockNum    int64          `json:"block_num"`
	FromAid     *int64         `json:"from_aid"`
	ToAid       *int64         `json:"to_aid"`
	GasUsed     *int64         `json:"gas_used"`
	TxIndex     *int32         `json:"tx_index"`
	NumLogs     *int32         `json:"num_logs"`
	CtrctCreate *bool          `json:"ctrct_create"`
	Value       pgtype.Numeric `json:"value"`
	GasPrice    pgtype.Numeric `json:"gas_price"`
	TxHash      string         `json:"tx_hash"`
	InputSig    *string        `json:"input_sig"`
}

type TxInput struct {
	ID       int64   `json:"id"`
	BlockNum int64   `json:"block_num"`
	TxID     int64   `json:"tx_id"`
	Data     *string `json:"data"`
}
