// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	// Layer-1 (blockchain infrastructure) queries.
	// Converted from hand-written SQL in internal/store; the sqlc-generated code
	// lives in internal/store/sqlcgen. See sqlc.yaml.
	GetAddressID(ctx context.Context, addr string) (int64, error)
	GetBlockByHash(ctx context.Context, blockHash string) (GetBlockByHashRow, error)
	GetEventLogByTxAndIndex(ctx context.Context, arg GetEventLogByTxAndIndexParams) (int64, error)
	GetLastBlockNum(ctx context.Context) (int64, error)
	GetTransactionID(ctx context.Context, txHash string) (int64, error)
	InsertAddress(ctx context.Context, arg InsertAddressParams) (int64, error)
	InsertBlock(ctx context.Context, arg InsertBlockParams) error
	SetLastBlockNum(ctx context.Context, blockNum int64) error
}

var _ Querier = (*Queries)(nil)
