#!/usr/bin/env python3
"""Regenerate scripts/seed-abi-events.sql from the Hardhat artifacts.

abi_events (db/migrations/00001) is the informational registry of event
signatures: the 4-byte prefix of keccak256(signature), the canonical
signature and up to six declaring contracts. The seed is built from every
artifact under artifacts/production of the Cosmic-Signature repo (the
production contracts, their interfaces, libraries and the test doubles that
share the build), so it must be regenerated whenever the contracts add or
change an event.

Usage:
    scripts/gen-abi-events-seed.py [COSMIC_SIGNATURE_DIR] > scripts/seed-abi-events.sql
"""
import json
import sys
from collections import defaultdict
from pathlib import Path

try:
    from Crypto.Hash import keccak
except ImportError:  # pragma: no cover
    sys.exit("pycryptodome is required: pip install pycryptodome")

DEFAULT_REPO = "/home/niko/eth/dev/b/cg-v3/Cosmic-Signature-v3.1-2026-08-19"
MAX_CONTRACTS = 6  # matches the width the original seed used

# Events the current sources no longer declare but the already-deployed
# V1/V2 game emitted; evt_log on production carries them, so the registry
# keeps describing them.
LEGACY_EVENTS = {
    "ArbitrumError(string)": {"CosmicSignatureEvents (pre-V3.1)"},
    "ERC20TransferFailed(string,address,uint256)": {"CosmicSignatureErrors (pre-V3)"},
    "CstRewardAmountForBiddingChanged(uint256)": {"ISystemEvents (pre-V2)"},
}


def canonical_type(inp: dict) -> str:
    """ABI type of one input, expanding tuples to (t1,t2,...)."""
    typ = inp["type"]
    if typ.startswith("tuple"):
        inner = ",".join(canonical_type(c) for c in inp.get("components", []))
        return "(" + inner + ")" + typ[len("tuple"):]
    return typ


def main() -> None:
    repo = Path(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_REPO)
    root = repo / "artifacts" / "production"
    if not root.is_dir():
        sys.exit(f"no artifacts at {root}; compile the contracts first")

    events = defaultdict(set)  # signature -> {contract names}
    for path in sorted(root.rglob("*.json")):
        if path.name.endswith(".dbg.json"):
            continue
        artifact = json.loads(path.read_text())
        abi = artifact.get("abi")
        name = artifact.get("contractName")
        if not isinstance(abi, list) or not name:
            continue
        for item in abi:
            if item.get("type") != "event":
                continue
            sig = f"{item['name']}({','.join(canonical_type(i) for i in item.get('inputs', []))})"
            events[sig].add(name)

    for sig, names in LEGACY_EVENTS.items():
        events[sig].update(names)

    rows = []
    for sig, names in events.items():
        h = keccak.new(digest_bits=256)
        h.update(sig.encode())
        rows.append((h.hexdigest()[:8], sig, ",".join(sorted(names)[:MAX_CONTRACTS])))
    rows.sort(key=lambda r: r[1])

    print("-- Generated by scripts/gen-abi-events-seed.py from artifacts/production")
    print(f"-- of {repo.name}.")
    print("INSERT INTO abi_events(signature, evt_name, contracts) VALUES")
    body = ",\n".join(f"\t('{sig8}', '{sig}', '{contracts}')" for sig8, sig, contracts in rows)
    print(body)
    print("ON CONFLICT (signature) DO UPDATE SET evt_name=EXCLUDED.evt_name, contracts=EXCLUDED.contracts;")


if __name__ == "__main__":
    main()
