
DROP TABLE IF EXISTS
	cg_prize_claim,
	cg_bid,
	cg_donation,
	cg_donation_received,
	cg_donation_sent,
	cg_charity_updated,
	cg_token_name,
	cg_mint_event,
	cg_nft_donation,
	cg_raffle_deposit,
	cg_raffle_withdrawal,
	cg_raffle_nft_winner,
	bw_raffle_nft_claimed,
	cg_donated_nft_claimed,
	cg_transfer,
	cg_contracts,
	cg_proc_status,
	cg_bidder,
	cg_winner,
	cg_raffle_winner_stats,
	cg_raffle_nft_winner_stats,
	cg_glob_stats,
	cg_round_stats,
	cg_nft_stats
CASCADE;
